### ISSUE TITLE
After destroying popper some inline styles are removed on the target

### ISSUE THREAD

**Issue by sylvaingi** [popperjs/popper-core#1001]
### CodeSandbox demo

https://codesandbox.io/s/friendly-forest-0p8ev

### Steps to reproduce the problem

1. Create a popper with a target using inline styles
2. Call popper.destroy()

### What is the expected behavior?

The target original inline styles should be preserved.

### What went wrong?

The inline style properties `position`, `left`, `top` and `margin` are removed, if they were initially present.

**Comment by atomiks** [comment]
https://github.com/popperjs/popper-core/pull/994

**Comment by FezVrasta** [comment]
This will be released as 2.0.6 today
