### ISSUE TITLE
Horizontal scrolling should scroll the popper if it caused an overflow.

### ISSUE THREAD

**Issue by And7s** [popperjs/popper-core#1006]
## Feature description

If a popper is wider than the current page width it will inevitably cause an overflow if inserted.

If now the user scrolls horizontally the popper will not be scrolled until the triggering element leaves the viewport. During the scroll interaction, the page will "grow" horizontally. as the popper body is sticking on the left side of the screen while the user is scrolling.

(resize the window to be smaller than 1000px. then scroll. the popper box will remain at left 0 until the triggering element reached 10 px before exiting the screen, then the popper starts scrolling)

https://codepen.io/aschmelz/pen/GRJowQw

recording: https://imgur.com/a/iObR0EP

This causes a unnatural scrolling behaviour.

if the popper element causes an overflow it should immediately be affected by any scrolling. 
This could be detected by checking if the popper is as wide as the page.clientWidth.

eg.  pseudo code

```
onScroll() {
  if (popperWidth == page.clientWidth) {
      return; // dont do anything but scroll the popper with the default behavior.
  } else {
    .. // current implementation to adjust the positioning
  }
}
```

## Why should this feature be part of the Popper's core?

having larger popper boxes than the viewport can happen in some cases. especially mobile willl be affected. In this case we want to have a natural way to explore the popper content (even though it caused an overflow initially)

**Comment by atomiks** [comment]
Other solutions:

- preventOverflow option `rootBoundary: 'document'`
- `max-width: 100vw;`
- A custom `size` modifier that adjusts the box's size to fit within the viewport so you scroll the box rather than the page to discover its extra content

**Comment by And7s** [comment]
thank you that also solves the issue perfectly:
here the modified codepen.

https://codepen.io/aschmelz/pen/GRJowQw
