### ISSUE TITLE
1.16.1 release missing from github

### ISSUE THREAD

**Issue by riconnon** [popperjs/popper-core#1008]
There seems to be a 1.16.1 release available from NPM, but there is no tag or release on Github and no release notes for it.
Is this an oversight? I would like to understand what changed in 1.16.1 compared to 1.16.0

**Comment by FezVrasta** [comment]
I’m not sure, this happened several months ago so I can’t remember the details.

Probably it fixed some publishing issues? I can’t tell it for sure.

**Comment by mixonic** [comment]
Tagging the release would still be helpful. I also spent a bunch of time digging for the tag to understand what had changed. The tag is there to help consumers understand what happens, that little happened is fine but the tag is how we find that out. 👍 🙇
