### ISSUE TITLE
Padding to prevent overflow does not calc overflowOffsets correctly

### ISSUE THREAD

**Issue by stevenjob** [popperjs/popper-core#1013]
### CodePen demo

https://codepen.io/stevenjob/pen/GRJWMBe

### Steps to reproduce the problem

1. create a popper with preventOverflow and padding of 8
2. see that popper is not squashed by 8px
3.

### What is the expected behavior?

should not have overflow-x
should have virtual padding of 8 on each side of popper and the popper should be squashed

### What went wrong?

i think the issue is in here
https://github.com/popperjs/popper-core/blob/master/src/utils/detectOverflow.js

### Any other comments?

I can add a pr for this when i get time (if it is even an issue)

**Comment by FezVrasta** [comment]
Popper never sets a width to the popper elements, so that means it can't possibly make your 100vw popper take less width than what your CSS defines.

I wouldn't consider this a bug, it's simply how the library works, by setting a so large popper you are breaking all the expectations we set when we wrote the library logic.

ping @atomiks

**Comment by stevenjob** [comment]
i think that was a mistake in my demo.
try now... https://codepen.io/stevenjob/pen/GRJWMBe

it does not matter what width i make my popper, even if i remove the width this issue still occurs

**Comment by stevenjob** [comment]
i can actually fix my issue by adding a max-width that has a calc to remove the padding.
https://codepen.io/stevenjob/pen/wvaJPxJ

should/could this be handled by popper?

if not then what is the point of the padding option? it only applies padding left and top?

**Comment by FezVrasta** [comment]
As I said, Popper never enforces popper widths, so I'd say what you are reproducing is expected.

The padding option is useful for normal-sized tooltips, when you need the tooltips to not touch the edges of their containers.
