### ISSUE TITLE
WANT TO SEE HOT PICS WITH ME? 💋 💋 💋

### ISSUE THREAD

**Issue by gromovadarya90** [popperjs/popper-core#1014]
WANT TO SEE HOT PICS WITH ME? 💋 💋 💋
👇 👇 👇

https://is.gd/ms4xm3

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
