### ISSUE TITLE
JavaScript exception thrown when using in iFrames

### ISSUE THREAD

**Issue by jacwright** [popperjs/popper-core#1018]
This is an issue with assumptions made by the `instanceOf` module.

The `instanceOf` module has methods `isElement` and `isHTMLElement` which check the constructor of a node against its own window's constructor. However, if the node was created by another document (namely the one in which the code is executing in), these checks fail.

The solution is to check against the node's window as well as the code context window and should have no impact on speed and negligible impact on code size.

### CodePen demo

https://codesandbox.io/s/gallant-williamson-1f0jf

### Steps to reproduce the problem

1. Add elements into an iframe after creating them from the document which is global to the executing code. Frameworks such as [Svelte](https://svelte.dev/) do this.
2. Create a tooltip within the iframe.
3. JavaScript exceptions are thrown.

### What is the expected behavior?

Popper should work without throwing exceptions when being used within an iframe. Iframes are used for sandboxing styles in use-cases such as 3rd-party widgets being installed on a page (e.g. a website chat widget).

### What went wrong?

An incomplete assumption is being held to determine if a node is an `Element` or `HTMLElement`.

### Any other comments?

The fix is simple, and I have confirmed it works, but I wanted to get feedback on the issue before submitting a pull-request or allow the project owners to make the fix since it is very simple.

```js
function isElement(node) {
  var OwnElement = getWindow(node).Element;
  // Add " || node instanceof Element" on the next line for elements created in the parent context
  return node instanceof OwnElement || node instanceof Element;
}

function isHTMLElement(node) {
  var OwnElement = getWindow(node).HTMLElement;
  // Same treatment here with HTMLElement
  return node instanceof OwnElement || node instanceof HTMLElement;
}
```

**Comment by FezVrasta** [comment]
Thanks for the report, a PR with your proposed solution would be welcome
