### ISSUE TITLE
wrong tooltip position/padding when boundary is set dynamically via setOptions()

### ISSUE THREAD

**Issue by jfu-maximago** [popperjs/popper-core#1020]
This is my very first issue report, therefore I hope it's helpful...

### CodePen demo

https://codepen.io/jfuhrmann/pen/bGdWEyx

### Steps to reproduce the problem

1. create a new popper instance with or without 'preventOverflow' modifier
2. setup the 'offset' modifier with some padding ([0, 8])
3. use popper.setOptions() and set 'boundary' of 'preventOverflow' modifier to a parent DOM element

### What is the expected behavior?

I expected that the tooltip has the correct position and padding.
'flip' modifier seems not to work properly.

### What went wrong?

Tooltip is missing the correct padding. It sticks directly to it's reference element.
Flip modifier does not take effect anymore.

**Comment by atomiks** [comment]
`.setOptions()` doesn't deep-merge the modifiers array, which means you need to spread in the previous modifiers
