### ISSUE TITLE
1.16.1 is broken via bower

### ISSUE THREAD

**Issue by dhoko** [popperjs/popper-core#1026]
:wave: 

The latest patch for 1.16.1 is broken when we install it via `bower`, it's fine via `npm`

### Steps to reproduce the problem

1. `npx bower install popper.js@1.16.0`
2. ls -l bower_components/popper.js 
3. there is a directory `dist`

4. `npx bower install popper.js@1.16.1`
5. ls -l bower_components/popper.js 
6. there is no directory `dist`

### What is the expected behavior?

We should have a directory dist with both versions, I don't see why if we look at this https://github.com/popperjs/popper-core/releases/tag/v1.16.1

### Any other comments?
Version 1.16.0

```
total 508K
-rw-r--r-- 1 dhoko dhoko  493 oct.  16 12:34 bower.json
-rw-r--r-- 1 dhoko dhoko  165 oct.  16 12:34 CHANGELOG.md
-rw-r--r-- 1 dhoko dhoko 3,2K oct.  16 12:34 CONTRIBUTING.md
drwxr-xr-x 4 dhoko dhoko 4,0K mars  11 09:47 dist/
drwxr-xr-x 9 dhoko dhoko 4,0K oct.  16 12:34 docs/
-rw-r--r-- 1 dhoko dhoko  169 oct.  16 12:34 lerna.json
-rw-r--r-- 1 dhoko dhoko 1,2K oct.  16 12:34 LICENSE.md
-rw-r--r-- 1 dhoko dhoko 2,9K oct.  16 12:34 MENTIONS.md
-rw-r--r-- 1 dhoko dhoko 1,3K oct.  16 12:34 package.json
drwxr-xr-x 9 dhoko dhoko 4,0K mars  11 09:47 packages/
-rw-r--r-- 1 dhoko dhoko  49K oct.  16 12:34 popperjs.png
-rw-r--r-- 1 dhoko dhoko  13K oct.  16 12:34 README.md
-rw-r--r-- 1 dhoko dhoko 397K oct.  16 12:34 yarn.lock
```

`npx bower install popper.js@1.16.1`
```
Version 1.16.1
total 496K
-rw-r--r-- 1 dhoko dhoko  165 déc.  18 20:33 CHANGELOG.md
-rw-r--r-- 1 dhoko dhoko 3,2K déc.  18 20:33 CONTRIBUTING.md
drwxr-xr-x 9 dhoko dhoko 4,0K déc.  18 20:33 docs/
-rw-r--r-- 1 dhoko dhoko  169 déc.  18 20:33 lerna.json
-rw-r--r-- 1 dhoko dhoko 1,2K déc.  18 20:33 LICENSE.md
-rw-r--r-- 1 dhoko dhoko 2,9K déc.  18 20:33 MENTIONS.md
-rw-r--r-- 1 dhoko dhoko 1,3K déc.  18 20:33 package.json
drwxr-xr-x 9 dhoko dhoko 4,0K mars  11 09:40 packages/
-rw-r--r-- 1 dhoko dhoko  49K déc.  18 20:33 popperjs.png
-rw-r--r-- 1 dhoko dhoko  12K déc.  18 20:33 README.md
-rw-r--r-- 1 dhoko dhoko 397K déc.  18 20:33 yarn.lock
```

**Comment by FezVrasta** [comment]
The release only affects the npm package. You can safely ignore it if you use Bower. I’ll fix it once I find some time though.

**Comment by dvincitravis** [comment]
Actually, I'm having the exact same problem (when installing 1.16.1 via Bower).

**Comment by fbalhawan** [comment]
Same issue here

**Comment by harbi** [comment]
The same issue (using Bower).

**Comment by FezVrasta** [comment]
> The release only affects the npm package. You can safely ignore it if you use Bower.

**Comment by FezVrasta** [comment]
Please, use 1.16.1-lts if you need Bower support.
