### ISSUE TITLE
Popper not keeping track of scrolling element

### ISSUE THREAD

**Issue by roostad** [popperjs/popper-core#1028]
Test case: https://jsfiddle.net/t8w57qj9/

### Steps to reproduce the problem

1. After table is done loading (5 sec), check popovers on cells of first column. They will look fine, positioned to right of first column.
2. Start scrolling horizontally on the table.
3. Now check the first column popovers again and the positioning will look strange as it's at the very left edge of the table.

### What is the expected behavior?

Popper should be tracking the positioning of the horizontally scrolling fixed column. I previously tried incorporating $('.pop').popover('update') to keep track of location but it is not working as intended.

### What went wrong?

Popover ends up at very left edge of table despite having been positioned to the right of tge first column. I have already checked with the DataTables team and the issue is not with them; they stated: "Popover not taking into account the position of the scrolling container, combined with the fact that the fixed column is position: absolute. It is probably initially positioning the popover well to the left, outside the scroll zone and then doing a check to see if the position is to the left of the scroll start and if so, moving it to that point."

**Comment by FezVrasta** [comment]
Hi, this is most likely fixed in popper v2, may you try with it?

**Comment by roostad** [comment]
I read the documentation for v2 and it recommended using tippy.js for a ready-to-go tooltip library. I implemented tippy as per the documentation but the tooltip is not triggered when I click on any of the cells in the first column. It could be a bootstrap 4 incompatibility issue but would you mind taking a quick look? https://jsfiddle.net/j0f7xrLt/ 

FYI, the new CDNs are on lines 7 and 8 of the HTML and I've modified the JS/HTML as well per the tippy documentation.

And sorry I don't mean to turn this into a tutorial :).

**Comment by roostad** [comment]
@FezVrasta v2 works like a charm, thanks!
