### ISSUE TITLE
Constructors

### ISSUE THREAD

**Issue by gaitat** [popperjs/popper-core#1030]
## Feature description

Currently the `createPopper` constructor requires a reference to an element. I assume that from this element the position and height are extracted in order to determine where the tooltip will go. 
This probably works for 95% of the time. In my case I am not using DOM elements to draw but WebGL. For each element that I need a tooltip I have the size and position. So it would help if a constructor would take an object like `{ x: number, y: number, width: number, height: number }` and compute where the tooltip should go.

**Comment by atomiks** [comment]
https://popper.js.org/docs/v2/virtual-elements/

**Comment by gaitat** [comment]
And if I have 1000 or even 10000 elements would I need that many calls to `createPopper` or is there a faster more optimal way?

**Comment by FezVrasta** [comment]
You can simply update the offsets reported by your virtual element.
