### ISSUE TITLE
Flow types do not work automatically

### ISSUE THREAD

**Issue by mcous** [popperjs/popper-core#1031]
The Popper v2 [documentation for usage with Flow](https://popper.js.org/docs/v2/typings/#flow) states:

> Rather than exporting limited type definitions, we link to the Flow-typed source files from the dist/umd folder.
>
> Flow will automatically read the exposed types, so you don't need to change any configuration in your project to take benefit from Popper typings.

In practice, I'm not finding this to be true.

### Steps to reproduce the problem

1. Set up the Popper recommended `.flowconfig`
    ```
    [declarations]
    ; read type signatures from node_modules but ignore flow errors within
    <PROJECT_ROOT>/node_modules/.*
    ```
2. Create a file that imports from Popper core
    ```js
    // @flow
    import { createPopper } from '@popperjs/core'
    ```
3. Hover over `createPopper` or try to assign it to a typed variable and notice that `createPopper` is typed as `any`

### What is the expected behavior?

- `createPopper` should be typed according to the types in its source code as stated in documentation

### What went wrong?

- `createPopper` is not typed

### Any other comments?

I'm pretty sure I'm not doing anything wrong, but please let me know if I am, in fact, doing something wrong!

From what I can tell, this problem is caused by the fact that the main types file `popper.js.flow` is located at `umd/popper.js.flow`, but `package.json::main` is `cjs/popper.js`, and there is no `cjs/popper.js.flow`. This seems like a fairly straightforward build misconfiguration in the rollup config, so I'm happy to PR a fix if this is the case!

I am also able to work around this by making the following changes in my `.flowconfig`:

```
[options]
module.system.node.main_field=module
module.system.node.main_field=main
```

I think this works because `package.json::module` is `lib/popper.js`, and `lib/popper.js.flow` exists. Even with that workaround, however, I'm still not able to do something like this:

```js
import type { Instance } from '@popperjs/core'
```

Instead, I have to do

```js
import type { Instance } from '@popperjs/core/lib'
```

`lib/index.js` / `lib/index.js.flow` exports all the types, but `lib/popper.js` / `lib/popper.js.flow` (the `package.json::module` entry) does not export any types.

Finally, I'm not sure what `dist/esm` is for compared to `lib`, and I don't see it referenced anywhere.

**Comment by FezVrasta** [comment]
Thanks for noticing! The types should be copied to `cjs`, a PR to fix that would be awesome.

**Comment by mcous** [comment]
@FezVrasta great, I can have a PR shortly!

Should any or all of `popper.js`, `popper-lite.js`, and `popper-base.js` also re-export types? i.e.

```js
export * from './types'
```

I believe this is necessary to achieve feature parity with the Typescript definitions:

```ts
// typescript
import { createPopper, Instance } from '@popperjs/core'
```

```js
// @flow
import { createPopper, type Instance } from '@popperjs/core'
```

**Comment by FezVrasta** [comment]
If we want `cjs` to be the `package.json::main`, then it should be enough to switch the `flow` flag on these two lines:
https://github.com/popperjs/popper-core/blob/master/.config/rollup.config.js#L16-L17

but maybe we actually want to use `umd` as `main`?

@atomiks, @trysound, ideas?

**Comment by mcous** [comment]
> If we want cjs to be the package.json::main, then it should be enough to switch the flow flag on these two lines:
> https://github.com/popperjs/popper-core/blob/master/.config/rollup.config.js#L16-L17

Yes, sorry, I should've mentioned that is unambiguously necessary. This change gets us Flow typed exports, but crucially, **does not get us exports of the type definitions themselves**.

From what I can tell, most of these type definitions live in the (well named) `src/types.js` file. So, what I'm proposing is, in addition to the rollup build change, the bundle entries themselves re-export the flow types _in their source files_.

The rollup flow config simply generates a file that points to the source entry, e.g. `src/popper.js`. Without type exports in those entry files, neither the cjs nor the umd entry points will appear (to Flow) to have any type definition exports.


```diff
diff --git a/.config/rollup.config.js b/.config/rollup.config.js
index 13a64b40..c01c9639 100644
--- a/.config/rollup.config.js
+++ b/.config/rollup.config.js
@@ -14,7 +14,7 @@ const inputs = ['src/popper.js', 'src/popper-lite.js', 'src/popper-base.js'];
 const bundles = [
   { inputs, format: 'umd', dir: 'dist', minify: true, flow: true },
   { inputs, format: 'umd', dir: 'dist', flow: true },
-  { inputs, format: 'cjs', dir: 'dist' },
+  { inputs, format: 'cjs', dir: 'dist', flow: true },
 ];

 const configs = bundles
diff --git a/src/popper-base.js b/src/popper-base.js
index f895822f..19173a0e 100644
--- a/src/popper-base.js
+++ b/src/popper-base.js
@@ -1,5 +1,7 @@
 // @flow
 import { createPopper, popperGenerator } from './index';

+export * from './types';
+
 // eslint-disable-next-line import/no-unused-modules
 export { createPopper, popperGenerator };
diff --git a/src/popper-lite.js b/src/popper-lite.js
index d8cb2d7a..21a29617 100644
--- a/src/popper-lite.js
+++ b/src/popper-lite.js
@@ -5,6 +5,8 @@ import popperOffsets from './modifiers/popperOffsets';
 import computeStyles from './modifiers/computeStyles';
 import applyStyles from './modifiers/applyStyles';

+export * from './types';
+
 const defaultModifiers = [
   eventListeners,
   popperOffsets,
diff --git a/src/popper.js b/src/popper.js
index bd6b0e05..e053f98b 100644
--- a/src/popper.js
+++ b/src/popper.js
@@ -10,6 +10,8 @@ import preventOverflow from './modifiers/preventOverflow';
 import arrow from './modifiers/arrow';
 import hide from './modifiers/hide';

+export * from './types';
+
 const defaultModifiers = [
   eventListeners,
   popperOffsets,
```

**Comment by mcous** [comment]
Ah my bad, didn't link the PR to the issue properly. This issue was fixed by #1036

**Comment by Sebastiansc** [comment]
@mcous is this fix live already? I'm experiencing this same issue on version 2.4.4

**Comment by FezVrasta** [comment]
Yes it is

**Comment by Sebastiansc** [comment]
@FezVrasta any idea why I woud be getting this error then?
<img width="991" alt="Screen Shot 2020-08-29 at 1 18 22 PM" src="https://user-images.githubusercontent.com/14895753/91645460-20d2c080-e9fa-11ea-9501-4bb68f9fe030.png">
<img width="769" alt="Screen Shot 2020-08-29 at 1 18 51 PM" src="https://user-images.githubusercontent.com/14895753/91645466-2fb97300-e9fa-11ea-8f7e-3f1da18b97bb.png">
