### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by gabskoro** [popperjs/popper-core#1040]
### Steps to reproduce the problem

1. Add `Import PopperComputeStyles from '@popperjs/core/lib/modifiers/computeStyles';` into your file
2. Use it inside the `modifiers` array
3. The code compiles fine and everything works
3. But when I run the test, it starts failing because `@popperjs/core/lib/modifiers/computeStyles.js` uses `import`. I guess because it's not being compiled

![image](https://user-images.githubusercontent.com/2737390/77565847-1d745f80-6ec5-11ea-8afc-09cfc8fdfe69.png)

Really weird, never had this error before, any clue guys what it could be? I'm running in Angular 9.0.6

**Comment by FezVrasta** [comment]
You should tell Jest to compile the `node_modules/@popperjs` folder. You can do that by setting `transformIgnorePatterns` to `['node_modules/(?!@popperjs)/']`.

**Comment by gabskoro** [comment]
Tnx! This didn't work alone (nothing happened), so I found out that I also needed to change my babel config, I'm using babel v7 but with `.babelrc` and this doesn't work, you need to use the `babel.config` file

Found it here https://github.com/facebook/jest/issues/7578#issuecomment-451671656

Maybe it helps someone else! :)
