### ISSUE TITLE
Missing dist/esm/package.json with "type":"module"

### ISSUE THREAD

**Issue by dilyanpalauzov** [popperjs/popper-core#1042]
With Node 13.11.0 I have in package.json {"type": "module"}.  I have installed popper.js 1.16.1 for use with bootstrap 4. 

When I call `node  node_modules/popper.js/dist/esm/popper.js` the error message is, that the keyword `export` is not recognized.

Please add in dist/esm a file package.json containing "type": "module".  This helps when i do `import Popper from 'popper.js/dist/esm/popper.js';`

**Comment by FezVrasta** [comment]
Thanks for the report, may you please point me to some documentation where this behavior is described?

**Comment by dilyanpalauzov** [comment]
This should be implied by https://nodejs.org/dist/latest-v13.x/docs/api/esm.html, it talks about `type:module`.  In any case, I described how to reproduce the case and what works for me.

I have a quesion to package.json for 1.16.1.  Its package.json contains: `"module": "dist/esm/popper.js", "unpkg": "dist/umd/popper.min.js"`.  Per the link above, Node continues to ignore `"module":`.  Where is unpkg described?

For making `import Popper from "popper.js"` work, the above documentatin recommends `"exports": {"import" : "./dist/esm/popper.js", "require": "./dist/umd/popper.js"}`. Can you give this format a try and upload popper.js 1.16.2?

**Comment by FezVrasta** [comment]
`unpkg` is defined here https://unpkg.com/

I'm not working on the 1.x branch anymore, we moved to 2.x, feel free to send a PR to improve the 2.x package.json if you feel like to.

**Comment by dilyanpalauzov** [comment]
As far as I can see with @popperjs/core@2.1.1 the same problem exists (in the current directory in package.json I have "type":"module"}) and I use node v13.12.0:
```
node node_modules/@popperjs/core/lib/popper.js
(node:28260) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/home/d/M/node_modules/@popperjs/core/lib/popper.js:1
import { popperGenerator } from "./index.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
Can you find a fix for 2.1.1 and with the gained expericne backport it to 1.16?

I do not feel experienced that much to provide PRs for node stuff.
```

**Comment by FezVrasta** [comment]
I'm struggling to find examples of other libraries placing a `package.json` in their `esm` dist folders... It seems like the `type: module` property is more commonly used for Node libraries.

**Comment by atomiks** [comment]
@dilyanpalauzov we probably won't be releasing a new `popper.js` version for this feature as it's in hibernation mode. But you can still add it yourself using [`patch-package`](https://www.npmjs.com/package/patch-package).

As for v2, I think we should wait until other libraries start adding `"type": "module"` to `package.json` in case it breaks anything...

**Comment by dilyanpalauzov** [comment]
I do think now that Conditional Exports
https://nodejs.org/api/esm.html#esm_conditional_exports are the way to go.

**Comment by FezVrasta** [comment]
THe problem with this is that you need to list every export, in our case, we want to allow to import all our utilities (even though we don't guarantee stability) and listing them all is not reasonable.
