### ISSUE TITLE
[Firefox] wrong positioning after switching from relative to fixed positioned parent

### ISSUE THREAD

**Issue by Klynger** [popperjs/popper-core#1043]
### CodePen demo
https://codepen.io/fothermucker/pen/mdJaRLq

### Steps to reproduce the problem

1. Open the demo in firefox
2. Scroll the page

### What is the expected behavior?

The tooltip should stay close to the element, as it happens in google chrome

### What went wrong?

The tooltip element starts to move down when you scroll

### Any other comments?

I have a component that implements a sticky behavior in order to have better support and it works 
just like this demo. You have a container element that wraps all the sticky elements, when the scroll hits the position of the `sticky-container` it puts a class to the `sticky-element` (`.fixed`) and the element stays at the top of the window and the reference element of the popper is inside of this `sticky-element`.

This bug doesn't happen in chrome or safari.

Thx guys :)

**Comment by atomiks** [comment]
You should change the strategy to `fixed` when you change the reference to be fixed position, it solves the problem.

**Comment by Klynger** [comment]
Oh, thx @atomiks. But you guys still plan to fix this issue in the default `strategy`?

**Comment by FezVrasta** [comment]
Yes I would expect this to work out of the box without custom config

**Comment by atomiks** [comment]
I don't think it should work out of the box, because changing the reference element's strategy changes its `scrollParents`, which requires the Popper instance to be updated (we can't re-check it on every update as it's expensive). 

In addition, changing the strategy to `fixed` is much better for positioning reliability in terms of glitches etc. if the reference is also fixed, so it should be done anyway.

```js
// if fixed && !classList.contains('fixed')
instance.setOptions({strategy: 'fixed'});

// if !fixed && classList.contains('fixed')
instance.setOptions({strategy: 'absolute'});
```

**Comment by atomiks** [comment]
This is the offending code:
https://github.com/popperjs/popper-core/blob/b58ebf0d488dd67b649d23afa9816b7a4a68e9ea/src/dom-utils/getOffsetParent.js#L17-L18

@FezVrasta what was the reason for adding this exception to Firefox again? As it's causing this problem now 😓
