### ISSUE TITLE
The ability to define the inline styles as !important

### ISSUE THREAD

**Issue by onassar** [popperjs/popper-core#1052]
## Feature description
I want to be able to define a flag (perhaps at object construction) that allows me to tell your library to define all inline styles on the popper as `!important`.

## Why should this feature be part of the Popper's core?
I don't think this should be on by default. But I do believe it should be an option to ensure the element styles are always adhered to.

## What's an example of when this could be useful?
I'm working on a Chrome Extension with your library, and some pages will override the inline styles because they don't have `!important` appended.

**Comment by FezVrasta** [comment]
Hi, this can be easily done by adding a custom modifier that maps data.styles to append `!important` over each value. I don’t think we need to implement this in the core.

**Comment by zeckdude** [comment]
@FezVrasta Can you please provide a code sample of how that can be accomplished for those of us who don't know how to create a custom modifier?

**Comment by hanguokai** [comment]
Hi @FezVrasta I see that Popper code use `Object.assign(element.style, style)` to apply styles. It is the same as `element.style.transform = style.transform`. But this method can't set `!important` to style, e.g. `element.style.transform = 'translate3d(917px, 1992px, 0) !important'` will fail, and the transform is 'none' now. For !important, it should be set by `element.style.setProperty("transform", "translate3d(917px, 1992px, 0)", "important")`. So I think custom modifier can't resolve this problem.

@zeckdude I have a work around method for this
`let state = await popper.update();
element.setProperty("transform", state.styles.popper.transform, "important");`
