### ISSUE TITLE
Popper appears in wrong position until browser reflow

### ISSUE THREAD

**Issue by brendanmc6** [popperjs/popper-core#1054]
Originally thought this was a tippyjs-react specific bug, but the maintainer @atomiks has asked that I post it here. Original issue: https://github.com/atomiks/tippyjs-react/issues/187

### CodePen demo
I hope it's ok that I re-use this repro that I had already posted on tippyjs-react
https://codesandbox.io/s/tippyjs-fixed-problem-7xmmd

### Steps to reproduce the problem

1. Open a popper inside of a `position: fixed` parent element, with the popper options set to `strategy: "fixed"`
2. Notice that it opens in the wrong position
3. Reflow the browser and it pops in to the correct position
![image](https://user-images.githubusercontent.com/9867865/78583600-e585ea00-77eb-11ea-91fa-7381c0eb32aa.gif)

### What is the expected behavior?
Opens in the correct location respecting `placement`

### What went wrong?
Opens in the wrong location, usually several hundred pixels below the desired placement.

### Any other comments?
Only hacky fix I have found is to force a reflow using window.scroll or other means.
Also see @atomiks comment here https://github.com/atomiks/tippyjs-react/issues/187#issuecomment-610026657

**Comment by atomiks** [comment]
Reproduced exclusively with popper: https://codesandbox.io/s/tippyjs-fixed-problem-fdep7
