### ISSUE TITLE
v1.16.1

### ISSUE THREAD

**Issue by weilinzung** [popperjs/popper-core#1056]
The latest version of `v1.16.1` is missing `dist` folder and all the scripts inside.

This would break anything with BOWER setup.

**Comment by FezVrasta** [comment]
The LTS version is not meant for Bower, it's dedicated to npm, to opt-out from the deprecation warning.

**Comment by weilinzung** [comment]
@FezVrasta compare of v1.16.0, why it is missing `dist` folder?  I have a package setup with `^1.16.0` which means I have to downgrade it to `1.16.0` by removing the `^`.

**Comment by FezVrasta** [comment]
I see, I need to figure out what's wrong with the deploy script.

**Comment by FezVrasta** [comment]
I should have fixed both 1.16.1 and 1.16.1-lts

**Comment by weilinzung** [comment]
@FezVrasta test again and all good, hopefully it would not happen again. thank you!

**Comment by FezVrasta** [comment]
Bower support has been dropped on Popper 2, so I'm certain it wont :-)

**Comment by weilinzung** [comment]
@FezVrasta yes and I know. Just some old projects still use it.

I am not an expert on releasing packages, so I have another question for you. How could you just rerelease 1.16.1 and 1.16.1-lts without changing their numbers?

**Comment by FezVrasta** [comment]
Bower releases are based on Git tags, you can delete, override, or move Git tags at your pleasure.

**Comment by weilinzung** [comment]
@FezVrasta Got it. thanks!
