### ISSUE TITLE
Documentation data-popper-* not updated

### ISSUE THREAD

**Issue by esso23** [popperjs/popper-core#1057]
This is really simple, so I'm not gonna use the template.
In the documentation there are attributes with names like `data-popper-placement` yet when I use the library the names are like this: `x-placement`.
Example: https://popper.js.org/docs/v2/tutorial/
I found this issue https://github.com/popperjs/popper-core/issues/483 so I figure it was changed recently but the docs weren't updated.

**Comment by FezVrasta** [comment]
I think you are still using Popper 1.x, where the attributes were prefixed by `x-x`.

In Popper 2.x they have the `data-popper-` prefix.
