### ISSUE TITLE
Scroll parents not tracked correctly through slotted elements.

### ISSUE THREAD

**Issue by Westbrook** [popperjs/popper-core#1059]
### CodePen demo
https://opensource.adobe.com/spectrum-web-components/components/dropdown

### Steps to reproduce the problem
1. Visit the above URL
2. Open the dropdown element in the "Example" section
3. Scroll the content
4. Watch the options list not scroll with this page

### What is the expected behavior?
Scrolling did not affect the location of the options list.

### What went wrong?
Scrolling for this element occurs in a parent of a `<slot>` element. Currently, the `getParentNode` code will not walk the correct branches of a DOM tree that projects content in this way.

### Any other comments?
Scrolling can be corrected by adding `element.assignedSlot ||` as the first optional return in the `getParentNode` helper:
https://github.com/popperjs/popper-core/blob/90cce7abe24d9fa6015beb7abb9aba0662c03203/src/dom-utils/getParentNode.js#L9-L15
I'd be happy to make a PR that includes this if you agree.

**Comment by atomiks** [comment]
> I'd be happy to make a PR that includes this if you agree.

Seems like it should be added yes, with a test if possible!

I don't think `|| document.ownerDocument || document.documentElement` actually makes sense in that expression, I think it should fallback to just `|| getDocumentElement(element)`, so perhaps add a fix for that too 🤔
