### ISSUE TITLE
Allow auto placements to be specified

### ISSUE THREAD

**Issue by atomiks** [popperjs/popper-core#1062]
## Feature description

`auto` chooses which placement to use (with most space), but you can't restrict which placements to use.

In this example, we only want to use `top` and `bottom`, but we still get the intrinsic "auto" behavior which is not achievable with the default `fallbackPlacements` option.

```js
modifiers: [
  {
    name: 'flip',
    options: {
      autoPlacements: ['top', 'bottom']
    }
  }
]
```

## Why should this feature be part of the Popper's core?

@FezVrasta wanted to use it 😄

**Comment by FezVrasta** [comment]
https://popper.js.org/docs/v2/modifiers/flip/#allowedautoplacements
