### ISSUE TITLE
bug: createPopper function using the same tooltip will not recalculate the style

### ISSUE THREAD

**Issue by Linkontoask** [popperjs/popper-core#1063]
### CodePen demo

[https://codepen.io/linkontoask/pen/bGVGXEP](https://codepen.io/linkontoask/pen/bGVGXEP)

### Steps to reproduce the problem

1. click 1 button
2. click 2 button

### What is the expected behavior?

Tooltip can be recalculated, Don't go beyond the view

### What went wrong?

I doubt whether the location of the tooltip has been cached in the createPopper function and will not be recalculated without affecting the location

**Comment by Linkontoask** [comment]
I found that if the view is scrolled, it will be recalculated.

**Comment by FezVrasta** [comment]
The demo you provided is not working, also, you are not supposed to call `createPopper` multiple times on the same elements

**Comment by Linkontoask** [comment]
The link can be accessed. Ask a question: why not call multiple times, each call should produce a new instance object

**Comment by FezVrasta** [comment]
You are applying two popper instances to the same tooltip, it can cause conflicts.

You should first call the `destroy` method

https://codepen.io/FezVrasta/pen/QWjwLLd
