### ISSUE TITLE
Why do we ship `src` on npm?

### ISSUE THREAD

**Issue by FezVrasta** [popperjs/popper-core#1064]
Does anyone remember why do we ship the `src` folder in our npm package? It's leading to some issues with Flow (because we use `__DEV__` which is not defined anywhere).

@atomiks do you have some context?

**Comment by atomiks** [comment]
You added it here https://github.com/popperjs/popper-core/commit/f8adb24d7af7b05424e137f4888a4c291fb9dd45 🤷

**Comment by FezVrasta** [comment]
Maybe I used it in place of `flow-copy-source`? 🤷‍♂️ Are everybody okay if I remove that folder from the npm package right?
