### ISSUE TITLE
visualViewport offset make hide and flip modifiers crazy

### ISSUE THREAD

**Issue by TrySound** [popperjs/popper-core#1074]
### CodePen demo

https://6z5bu.csb.app/
https://codesandbox.io/s/loving-feather-6z5bu

### Steps to reproduce the problem

1. open xcode ios simulator
2. toggle software keyboard
2. focus input
3. scroll up and down, hide attribute is applied when input is in viewport

### What is the expected behavior?

Hide attribute should be applied only when input is out of visible viewport

### What went wrong?

visualViewport offsets breaks hide and flip modifiers

**Comment by atomiks** [comment]
I guess we should've known the iOS implementation of this thing would be terrible 🤦should we feature detect iOS and use `0` for it? Otherwise pinch zooming on Chrome Mac is broken and maybe other things
