### ISSUE TITLE
Nested VirtualElement - change in behaviour from V1 to V2

### ISSUE THREAD

**Issue by sgilligan** [popperjs/popper-core#1077]
I have a test case where a popper based on a virtual element housed within a relative container behaves differently between popper v1.16.1 and v2.3.1.

A: https://codesandbox.io/s/nested-popper-1-jvhhf?file=/src/Example.jsx
B: https://codesandbox.io/s/nested-popper-2-gdbm2?file=/src/Example.jsx 

### What is the expected behavior?
I was expecting test case B (using version 2 of the library) to behave as with test case A. That is, the div with text content 'Popper' to be within the white square.

 Am I using the API correctly for test case B, or is this a bug?

**Comment by atomiks** [comment]
This seems correct — `getBoundingClientRect` is always relative to the viewport, not a container element.

**Comment by sgilligan** [comment]
thanks @atomiks - both A and B popper test cases are the same implementation, both positioned as virtual elements, both using `getBoundingClientRect`, the only difference is the version of the library (2.3.1 vs 1.16.1) 

- If version b is the correct behaviour (2.3.1), is the behaviour of the version (1.16.1) release then incorrect? 

- how would I implement a Virtual Element that positioned relative to the container?  (I have application behaviour based around test case A which now breaks with 2.3.1)

**Comment by atomiks** [comment]
Yes v1 is incorrect. You need to get the `getBoundingClientRect` of the container add them to your offsets of the virtual element.

`top: container.top + 40`
`left: container.left + 40`

**Comment by sgilligan** [comment]
understand, thanks @atomiks, will close.  Cheers.
