### ISSUE TITLE
Wrong Popper position in a scrolled content

### ISSUE THREAD

**Issue by alex3ax** [popperjs/popper-core#1078]
### CodePen demo

https://codepen.io/alex3ax/pen/qBOONPW

### Steps to reproduce the problem

1. Scroll a little bit down
2. Click on the button
3. The tooltip position is wrong

### What is the expected behavior?

The tooltip should be stuck to the bottom of the button

### What went wrong?

The scrollTop of the ref is always 0 in this example, it looks like the offset calculation can't take scroll into account. 

### Any other comments?

Given such a layout is it possible to configure the Popper behavior correctly without layout changes?

**Comment by atomiks** [comment]
I think this is the visualViewport thing to be honest, it doesn't happen in `2.2.0`. We've fixed it already, waiting for release right now.

**Comment by atomiks** [comment]
Okay so, took a look again.

It's caused by making `<html>` a scroll parent (`overflow` property). I would highly recommend not styling `<html>` at all beyond a CSS "reset" or adding `height: 100%`, but this is an edge case that needs to be fixed I guess.

I believe it's this:

https://github.com/popperjs/popper-core/blob/1976cdc48c5e556cfd4bf7faf162536c16aa6558/src/dom-utils/getScrollParent.js#L8-L11

**Comment by alex3ax** [comment]
Thanks for your efforts @atomiks, really appreciate it. Unfortunately, the layout is beyond our control - we add our widget to the clients' websites and have to deal with such cases.

**Comment by Slapbox** [comment]
Having (seemingly) the same issue after updating `react-popper` from `2.1.x` to `2.2.2` in a `contentEditable` with potentially unusual overflow and other styles (Electron app.)

**Comment by atomiks** [comment]
@Slapbox create a reproduction, it's virtually impossible to know why it's happening because DOM edge cases are crazy

**Comment by Slapbox** [comment]
Poking through my `yarn.lock` it looks like we've mysteriously updated to `popper-core` to latest, though I can't figure out why. Anyway, if the PR you've got open doesn't fix it I'll downgrade or be back.
