### ISSUE TITLE
Vue wrapper for popper

### ISSUE THREAD

**Issue by codebender828** [popperjs/popper-core#1085]
## Feature description
Hello Popper team. Thank you for the great work you're doing with Popper. Love it. 

I was going through some of your organizations repositories and I noticed you have some wrappers for Popper for React and Svelte.

A couple of months ago I happened to work on a Vue wrapper for Popper. I thought you might be interested in it. 

Here's a link to the repo!

https://github.com/codebender828/popper-vue/blob/master/README.md

Live Demo:
https://codesandbox.io/s/popper-vue-starter-nipsz

Happy to hear your thoughts. Cheers!

**Comment by atomiks** [comment]
Great work! It looks like you started work a month before v2 was released and so it's using v1 currently, any plans to upgrade it to v2?

**Comment by codebender828** [comment]
Thanks! Yeah, sure I can do that probably during the course of the week. 👍 Thanks for the great work. Any suggestions on the implementation?

**Comment by FezVrasta** [comment]
What I'm looking for from a Popper wrapper is something very low-level, it should provide the same functionalities provided by the base library, without additional show/hide/rendering functionalities.

**Comment by FezVrasta** [comment]
I'm going to close this issue to keep the repository tidy, since it's not something related to Popper core, but feel free to continue the conversation here.

**Comment by codebender828** [comment]
> What I'm looking for from a Popper wrapper is something very low-level, it should provide the same functionalities provided by the base library, without additional show/hide/rendering functionalities.

Alright. Noted. Will upgrade to Popper 2 and keep the conversation here. I'll have some free time on Friday, so we'll have something then. Will keep us posted. Cheers!

**Comment by iamandrewluca** [comment]
https://github.com/allindevelopers/vue-floating-ui
