### ISSUE TITLE
Unmerged changes pending (causing `transform: scale` to not be accounted for)

### ISSUE THREAD

**Issue by Domiii** [popperjs/popper-core#1086]
The fix for [transform: scale(...)](https://github.com/popperjs/react-popper/issues/73) (discussed on `react-popper`) never made it into `popper-core`.

[Here is the fixed version](https://github.com/rfrey-imb/popper.js/blob/add166ea75be347081990674f346031575b3dac3/packages/popper/src/utils/getBoundingClientRect.js) [[diff here](https://github.com/rfrey-imb/popper.js/commit/add166ea75be347081990674f346031575b3dac3#diff-4755b8533dd4d75c819550582c761b60)].

[Here is the current `getBoundingClientRect`](https://github.com/popperjs/popper-core/tree/master/src/dom-utils/getBoundingClientRect.js).

Any idea when this will get merged?

**Comment by atomiks** [comment]
I think using the popper as a styleless wrapper element around an inner box element is the better way to do this. See https://popper.js.org/docs/v2/faq/#how-do-i-add-css-transitions-without-disabling-adaptive

**Comment by Domiii** [comment]
@atomiks I'm not sure I understand how that applies to my case? I am having a map-like element that uses `transform` for panning and zooming (specifically using the `panzoom` library). Inside of that element I want to have some `popper` popups, but they end up in the wrong place if you zoom out or pan around. Applying the `popper` class to the entire map seems like overkill, doesn't it?

Maybe going for a more complete map library solution instead might be the better way of going about doing this after all? :)

**Comment by atomiks** [comment]
Sounds different to what I imagined, can you make a demo for us to investigate?

**Comment by FezVrasta** [comment]
We do address for transforms, as you can see from this example:
https://codesandbox.io/s/silly-pine-lbmoh?file=/index.html

I'll close it for now, we can reopen once OP provides a repro.

**Comment by Domiii** [comment]
Dynamic `transform`s (such as what you would have with "map"-like elements, or anything using the `panzoom` library) do not work:
https://codesandbox.io/s/holy-sound-lp5qj?file=/src/index.js

**Comment by atomiks** [comment]
Don't you just need to call `popperInstance.update()` when a `pan` event fires?

**Comment by FezVrasta** [comment]
Yeah it's enough to trigger an update after the transformation changes, Popper doesn't track DOM mutations, you need to track them yourself.

https://codesandbox.io/s/hopeful-leaf-l2sx6?file=/src/index.css
