### ISSUE TITLE
Type error in computeStyles.js.flow

### ISSUE THREAD

**Issue by EnoahNetzach** [popperjs/popper-core#1091]
### Steps to reproduce the problem

1. `yarn add @popperjs/core` 
2. use popper
3. `yarn flow check`

### What is the expected behavior?

No type errors should be printed

### What went wrong?

Flow reports this error:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/@popperjs/core/lib/modifiers/computeStyles.js.flow:93:9

Cannot spread adaptive && unsetSides because boolean [1] is not an object.

 [1] 49│   adaptive,
       :
     90│
     91│   const commonStyles = {
     92│     position,
     93│     ...(adaptive && unsetSides),
     94│   };
     95│
     96│   if (gpuAcceleration) {


```

### Any other comments?

Using
- `@popperjs/core: 2.3.3`
- `flow-bin: 0.109.0`

**Comment by FezVrasta** [comment]
You are using an old Flow version, spreading booleans is supported by JS and doesn’t error in recent Flow versions

**Comment by EnoahNetzach** [comment]
I know, but I can't upgrade to the latest flow version unfortunately, and the fix is actually more expressive...
