### ISSUE TITLE
No option to hide popper if it overflows viewport

### ISSUE THREAD

**Issue by jeffcstock** [popperjs/popper-core#1101]
### Is there a way to easily hide the popper if it overflows the viewport?
![image](https://user-images.githubusercontent.com/13420097/81122487-ce6b1280-8ee5-11ea-8222-17fab60f1ef7.png)

### CodeSandbox demo

https://codesandbox.io/s/autumn-sunset-896j7?file=/src/index.js

### Steps to reproduce the problem

The problem is that I cannot hide the popper if it is pushed outside the screen.

1. Collapse the window so that the popper is pushed off-screen.
2. The popper is not hidden.

Note that I've tried the `hide` modifier, but from what I understand, it deals with what happens to the popper element **when the reference element is pushed off screen.**

I'm looking at `hasPopperEscaped: false` specifically.

Is there any way to accomplish this?

### What is the expected behavior?
I would like the option to be able to hide the popper overlay element if it will overflow.

If it flips and still has enough room to display nicely, that's fine, but the problem is I don't want to cover the reference element.

### What went wrong?

The popper just extends past the screen. If I turn on `showOverlay`, then it just displays overtop the reference element, which is not ideal.

### Any other comments?

If this isn't a current option, then I think it could be added!

**Comment by atomiks** [comment]
You can add this functionality using [`detectOverflow`](https://popper.js.org/docs/v2/utils/detect-overflow/)

**Comment by jeffcstock** [comment]
Thanks @atomiks. Missed that.
