### ISSUE TITLE
Position transition

### ISSUE THREAD

**Issue by DaniGuardiola** [popperjs/popper-core#1103]
Note: sorry about the lack of template, but this is half question half suggestion so i didn't know how to format this correctly.

I want to add a position transition to my popper element.

What I mean by this: once the popper has been created I want it to behave as with the `transition: transform 0.2s;` CSS rule whenever the position changes.

The issue I'm having is, if I add that rule to the popper element directly, the transition applies to the first update, which means the element visibly enters the screen from the edge, as the transform property has changed internally. The same happens when it exits.

I would like to be able to add this CSS rule but only from the moment after the initial position (creation) has been set, up to the moment before the final position (destruction) is set.

Does this make sense? I couldn't find a way to implement this. I'm using material UI, btw, which uses the 1.x version, but I would like to:

1. Find out if there's a clean way to achieve this in the current versions or
2. suggest that this use case is covered in future releases.

Thank you! :)

**Comment by FezVrasta** [comment]
You should use the onCreate callback to set the class to enable the transition. You can then remove it before calling the destroy method
