### ISSUE TITLE
using low level dom/positioning code

### ISSUE THREAD

**Issue by mreinstein** [popperjs/popper-core#1106]
I'd like to use the low level positioning code of popper, which is super awesome in other places.

I guess really what I want is some kind of api where given:
* a dom element with popper content
* a dom reference element in the document (the thing the popper should stay snapped to)

get an object back that has the details on where to position the popper content.

I've looked at the code a little bit, and it seems like the "meat" of that logic is in src/dom-utils/

Is there kind of an "entry point" into dom-utils/ ?  A large chunk of those modules are helper functions.

Should I be looking at a particular modifier for how to call this?

Any pointers would be greatly appreciated on these low level pieces.

thanks again for an _amazing_ library!

**Comment by miracle2k** [comment]
I'm looking for something similar, but without the DOM. Is it reasonable to give the anchor bounds, the element bounds, the screen bounds and have popper do the math?

**Comment by FezVrasta** [comment]
@mreinstein you can do that, when you call `createPopper`, the call returns an [instance](https://popper.js.org/docs/v2/constructors/#instance), with a `state` containing all the computed coordinates.

If you disable the [`applyStyles`](https://popper.js.org/docs/v2/modifiers/apply-styles/) and [`eventListeners`](https://popper.js.org/docs/v2/modifiers/event-listeners/) modifiers you get a one-time call function that returns the data you required.


@miracle2k unfortunately, at the moment, Popper can only work in a DOM environment, I'd like to add support for other environments (such as React Native) but it'd require a lot of work to make it possible. Said that, Popper 2 has been wrote from the ground-up to make this possible, it just requires more work to implement the support.

**Comment by mreinstein** [comment]
@miracle2k honestly without the dom, the library itself isn't that helpful. Most of the value of the positioning logic that popper provides is coming from the complexity/insanity of dealing with terrible dom/css layout rules.

If you're just dealing with pure layout rectangles the math is pretty simple, like 50 lines or less.

**Comment by miracle2k** [comment]
@mreinstein Yeah, but it is still 50 lines with a fairly dense logic burden, so it would be nice to have in a reusable library.

**Comment by mreinstein** [comment]
@FezVrasta I'm hacking around with some low level functions in popper, is this a good place to throw questions, or is there a gitter/slack/discord community that would be easier/more appropriate?

**Comment by FezVrasta** [comment]
We have a Spectrum community https://spectrum.chat/popper-js?tab=posts
