### ISSUE TITLE
Popper Performance improvements: does too much  style recalculation

### ISSUE THREAD

**Issue by pareshchouhan** [popperjs/popper-core#1107]
## Feature description

Improve performance of popper
Popper right now takes getOffsetParent() which takes more than 150ms and does style recalculation 

Total Time156.80 ms
Self Time156.80 ms
Elements Affected: 924

## Why should this feature be part of the Popper's core?
Not sure

**Comment by FezVrasta** [comment]
Have you noticed any lag or jitter?

**Comment by lkraav** [comment]
Also, what's the alternative?

**Comment by pareshchouhan** [comment]
I can do a performance analysis and suggest ways to improve performance and then we can discuss about those, sounds good?

**Comment by pareshchouhan** [comment]
> Have you noticed any lag or jitter?

I have noticed framedrops, and excessive style recalculation that chrome Dev tools keeps flagging as warning

**Comment by pareshchouhan** [comment]
> Also, what's the alternative?

Not looking for an alternative, let's fix it :)

**Comment by FezVrasta** [comment]
Perf improvements are always welcome, but I don’t know if there are lighter APIs we can call to get the same results

**Comment by pareshchouhan** [comment]
There are no lighter APIs, but doing CSS style updates and other CSS
changes inside a requestAnimationFrame will do wonders, if we aren't
already doing it.

**Comment by FezVrasta** [comment]
Right now we throttle the updates using a microtask, I'd be curious to see if `requestAnimationFrame`, maybe used inside `applyStyles` could help.

**Comment by pareshchouhan** [comment]
I hope it does, what I found out was,

We were using react-tippy that used popper is internally and most of the
work was being done in style recaclulation in popper is (230ms! I might
have that flame graph around, I will have a look), so the choice was either
remove popper or fix it :)

**Comment by pareshchouhan** [comment]
Okay, seems like a react-tippy issue, popper wasn't doing anything at all...

I will still have a look at poppers code just to see if there are any frame drops because of anything that it does.
![tippycausing_force-re-render](https://user-images.githubusercontent.com/1715271/82232505-5ae8ec80-994c-11ea-8477-e348faed0f60.png)

**Comment by pareshchouhan** [comment]
Opened an issue in tippy, please close it. https://github.com/tvkhoa/react-tippy/issues/136
