### ISSUE TITLE
Sometimes, a popper renders super out of whack in positioning

### ISSUE THREAD

**Issue by runfaj** [popperjs/popper-core#1108]
### CodeSandbox demo

Haven't been able to reproduce in a sandbox, but I'll include a couple gifs.

### Description

There's 2 issues, both appear when nesting poppers via popperjs 2.4.0 (via my package https://github.com/runfaj/react-nested-popper):

1) on popper init
by calling `this.popperInstance = createPopper(...);`, sometimes the placement is off. In this gif, the placement is set to "left", but appears on the right until a scroll or resize event happens.
![](http://g.recordit.co/Et8pJ5uHiB.gif).
This one is fixed by adding something like
```
setTimeout(() => {
  if (this.popperInstance) {
    this.popperInstance.update();
  }
});
```
immediately after the createPopper call. However, this causes a noticeable flicker occasionally as the placement updates.

2) on popper option update
by calling `this.popperInstance.setOptions(this.popperOptions);` in something like a react componentDidUpdate, we get behavior like this:
![](http://g.recordit.co/RGgaFMrhRK.gif)
If I remove the setOptions call, this works as expected. If I keep that setOptions and add the same setTimeout as (1), then it also works, but the flickering is very noticable.
(this image shows it happen once, but the framerate of the gif isn't super great to show it happening with every key press)
![](http://g.recordit.co/8R7iHnnxue.gif)

For reference, here's my componentDidUpdate cycle as it currently stands.
```
  componentDidUpdate(prevProps) {
    // watch prop changes to see if we need to init or update the popperjs instance
    // if not show, we kill the instance and clean up refs
    if (this.props._show) {
      if (!this.popperInstance) {
        this.initPopperInstance();
        this.forcePopperUpdate(); // does the setTimeout update mentioned
      } else if (!_isEqual(this.props.popperOptions, prevProps.popperOptions)) {
        this.popperInstance.setOptions(this.props.popperOptions);
        this.forcePopperUpdate(); // does the setTimeout update mentioned
      }
    } else {
      this.destroyPopperInstance();
    }
  }
```

### Expected
I would expect that createPopper and setOptions call their update cycles immediately after setting configurations before ever rendering an update to the browser to position correctly as well as prevent flickering.

Also, having the update method async (as it currently is) could also be an issue. If it was synchronous, we could control more easily how and when the cycle should update after options change.

### Additional Info
I suspect (1) in the example above is actually also an issue of (2). My popper initializes, but then another update cycle can potentially change the popper options. When I added that _isEqual in the example, the problem was significantly reduced in both cases. However, there is definitely an issue with the setOptions causing the placement to go in weird spots.

**Comment by FezVrasta** [comment]
Is there any reason why you are not using react-popper? It supports nested poppers just fine.

Unfortunately I can’t help you without a reproduction demo.
