### ISSUE TITLE
Tooltip can flip too early 

### ISSUE THREAD

**Issue by skvale** [popperjs/popper-core#1110]
### CodeSandbox demo

https://codesandbox.io/s/dry-water-t02k7

### Steps to reproduce the problem

1. Open the popper (it has placement bottom)
2. Shrink the viewport a bit, by opening devtools or moving the codesandbox console up
3. Observe the tooltip flip to the top when there is plenty of room on the bottom

![popper2-bug](https://user-images.githubusercontent.com/5314713/82591964-c1952280-9b65-11ea-8b12-d8cbf20ee1c7.gif)

### What is the expected behavior?

Since the position is "bottom" it should behave like it typically does, only flip to the top when it goes off-screen

### What went wrong?

I think I've narrowed it down to 3 things needing to happen
- html has style of `height 100%`
- body has styles for `overflow-x: auto` and `height: 100%`
- a containing div has `position: relative;`

### Any other comments?

I saw this issue in an app using Bootstrap, so it might not be a far-fetched perfect storm of style configurations.

**Comment by atomiks** [comment]
I think the problem is the `<body />` doesn't stretch the entire actual scrollable page/area, but is a clipping parent, so it thinks it's overflowing it. In your case I think you need to set `boundary: []` for the `flip` modifier.

Also you should wrap the `show &&` condition around the whole popper element to prevent the jump/incorrect position on first show.

https://codesandbox.io/s/confident-leaf-63kz2?file=/src/App.js

**Comment by skvale** [comment]
Thank you, the `boundary: []` does fix it.  I'm curious about what's going on there.  I read the docs for boundary:
> This describes the area that the element will be checked for overflow relative to.

> By default, it is "clippingParents", which are the scrolling containers that may cause the element to be partially or fully cut off.

So what does an empty array mean?

**Comment by atomiks** [comment]
The type is `type Boundary = 'clippingParents' | HTMLElement | Array<HTMLElement>` so in essence, you're specifying no elements to be used as the boundary with an empty array (like `null`). The `RootBoundary` (default `viewport`) is still in effect though

**Comment by skvale** [comment]
This works great for the `preventOverflow` and `flip` modifiers, but I can't add this option to the `hide` modifier, which has the same issue.
