### ISSUE TITLE
Strategy "fixed" invalid position in containing block

### ISSUE THREAD

**Issue by wszydlak** [popperjs/popper-core#1111]
### CodeSandbox demo

https://codesandbox.io/embed/dazzling-leftpad-cszp1?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce the problem

1. Set `strategy` to `fixed`
2. Place popper element inside [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block)
3. Popper element will not calculate it's fixed position related to containing-block, but will calculate position related to `window`

### What is the expected behavior?

With `strategy` fixed popper should find nearest containing block parent and calculate position related to this containing block.

### What went wrong?

Position has been calculated incorrect.

### Any other comments?

⚠️ This was working properly in popper@1
Also placement works fine with strategy `absolute`

**Comment by atomiks** [comment]
https://github.com/popperjs/popper-core/issues/1035

**Comment by wszydlak** [comment]
@atomiks 

Don't understand your point of view. According to CSS Specification: https://drafts.csswg.org/cssom-view/#dom-htmlelement-offsetparent `offsetParent` will always return `null` in case where element has position `fixed`, `will-change` doesn't  change anything there. Additionally strategy `fixed` is broken in every browser and in this case I expect for library to do calculactions better. I thing that you should consider options:

1. Remove deprecated flag in popper@1, cause popper@1 worked better than popper@2 for strategy `fixed`
2. Do some calculations in popper@2 to ensure you do element placement related to containing block.
3. Maybe there should be extra strategy for this use case (containing blocks)
4. Maybe you can give user option to manually set offset-parent, then we can do calculations on our side, eg. config option:

```
function getOffsetParent(element, popperOffsetParrentGetter) {}
```

then user could simply do something like that:

```
{
  getOffsetParent: (element, popperOffsetParrentGetter) {
    let offsetParent = popperOffsetParrentGetter(element);
    if (!offsetParent || offsetParent === window) {
      offsetParent = customParentCalculation(element);
    }
    return offsetParent;
  }
}
```

For now we are blocked and can't do anything to make this work and for now we need to stay with popper@1, but it always warns that is deprecated.

Please do something with that.

**Comment by FezVrasta** [comment]
@atomiks actually even if I remove `will-change: transform` the bug can still be reproduced. It seems to be a different issue.

https://codesandbox.io/s/small-feather-n99pf

**Comment by FezVrasta** [comment]
@wszydlak the problem is described in the ticket @atomiks linked above, there's a bug in the browsers implementation of `transform` that makes so that `fixed` elements get positioned relatively to the `transform` parent rather than the document viewport. The browsers don't report this kind of parent as an `offsetParent` so there's no way to detect them in a performance sensitive way.
