### ISSUE TITLE
Popover is misaligned when certain html styles are applied

### ISSUE THREAD

**Issue by skvale** [popperjs/popper-core#1112]
### CodeSandbox demo

https://codesandbox.io/s/dry-water-t02k7

<img width="671" alt="Screen Shot 2020-05-22 at 1 08 59 PM" src="https://user-images.githubusercontent.com/5314713/82697059-dfc65580-9c2d-11ea-8c42-d9174c1e0c07.png">

![popper2-bug-2](https://user-images.githubusercontent.com/5314713/82697172-04bac880-9c2e-11ea-9fbc-1cb9535ec0ab.gif)

### Steps to reproduce the problem

- Open the popper (it has placement right)
- Shrink the viewport a bit by opening devtools or moving the codesandbox console up
- Observe the tooltip is aligned too high
- Remove any of the styles from body/html height 100% or overflow-x: hidden or the position relative wrapper and see it fix itself.

### What is the expected behavior?

the body/html and relative wrapping styling should not warp the alignment.

### What went wrong?

Similar to https://github.com/popperjs/popper-core/issues/1110

- html has style of height 100%
- body has styles for overflow-x: auto and height: 100%
- a containing div has position: relative;

### Any other comments?

The fix from https://github.com/popperjs/popper-core/issues/1110 does not work for this issue

**Comment by atomiks** [comment]
I think it's the same issue, you just need to apply it to `preventOverflow` as well as `flip`
