### ISSUE TITLE
html { position: relative } breaks scrolling

### ISSUE THREAD

**Issue by felixscheinost** [popperjs/popper-core#1114]
### CodeSandbox demo

https://codesandbox.io/s/clever-clarke-lwebh?file=/index.html

### Steps to reproduce the problem

1. Make tooltip very long so that it requires scrolling 
2. Add CSS `html { position: relative }` 

### What is the expected behavior?

When scrolling the tooltip scrolls with the button.

### What went wrong?

The tooltip stays in the same position (is moved by popper). Page can be scrolled infinitely. 

### Any other comments?

`html { position: relative }` might not be sensible so I am not sure if this is a bug. But still, the scrolling behaviour seems kind of weird so I am hoping on your input.

One workaround is to simply add another container with `position: relative` around the tooltip and button: https://codesandbox.io/s/competent-proskuriakova-703dp?file=/index.html

**Comment by FezVrasta** [comment]
It seems to happen only on Firefox, may you confirm?

**Comment by felixscheinost** [comment]
Thanks for the quick response!

Huh, didn't notice that. But yes, can confirm it only happens on Firefox.
