### ISSUE TITLE
Strategy "fixed" not working fine for popper@2

### ISSUE THREAD

**Issue by wszydlak** [popperjs/popper-core#1115]
According to: #1035 I want to continue this topic, don't know why you said that my tone is over the top, but I'm sorry if I offended you.

But to continue I sent you examples, potencial function which made it working better in popper@1 and polite asked you to reopen issue, due to bug in popper@2

**Comment by atomiks** [comment]
You can create a PR that checks for the properties that create a containing block on parents and see if it doesn't kill perf, or add an `unstable_getOffsetParent` option to Popper that allows users to specify their own `getOffsetParent` DOM util so they can specify a custom element or detect "containing blocks" which `.offsetParent` can't.
