### ISSUE TITLE
The looping occurs and the browser hovers

### ISSUE THREAD

**Issue by stsiushkevich** [popperjs/popper-core#1116]
Hello! 

I  encountered the problem with popper not the first time when a tooltip isn't fit in a certain container. The looping occurs and the browser hovers. The "boundariesElement" attribute doesn't help each time.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
