### ISSUE TITLE
Browser hangs when using renderprop inside reference element, while also using offset function

### ISSUE THREAD

**Issue by reywright** [popperjs/popper-core#1117]
### CodeSandbox demo

https://codesandbox.io/s/happy-dawn-0mqdh

### Steps to reproduce the problem

1. Put a render prop inside the reference element.
2. Pass a function to the `offset` modifier.

(this has already been done in the sandbox, just click the button)

### What is the expected behavior?

That it shows the popover and works, the same as if the modifier was  `offset: [0, 0]`

### What went wrong?

The browser / iframe will hang and the popover won't show.

### Any other comments?

Note: again, the following works perfectly fine:

```         
options: {
  offset: [0, 0]
}
```

I'm unclear why the function breaks things here.

**Comment by atomiks** [comment]
This seems like a `react-popper` issue, can you open an issue on that repo?
