### ISSUE TITLE
Add more examples and code snippets and documentation.

### ISSUE THREAD

**Issue by AmirTugi** [popperjs/popper-core#1118]
## Feature description
Fill this library with examples for as many use cases as people think of

## Why should this feature be part of the Popper's core?
This library is a great one, and the fact that it's being integrated in big style-guides means a lot.
I find it, as a user, that it's rather hard to achieve what I want to by looking at the documentation.
I don't find it guiding me to what I want to achieve.

* Say, when looking at demos in the documentation I find the exact example I want to implement.
But I cannot find the code for that!
That makes me frustrated, and I wonder around trying to gather pieces of information on how to do that exact demo.

* Or sometimes in the documentation is lacking of explanation on [implementation](https://popper.js.org/docs/v2/modifiers/arrow/#data) (where do I put this `data` object?)

I would love to add some use cases and the code for it.
But unfortunately I can't manage understanding how to best use this lib.

> **Edit by the maintainer:**
> A possible solution for this ticket is described [here](https://github.com/popperjs/popper-core/issues/1118#issuecomment-640621515)

**Comment by FezVrasta** [comment]
Thanks for the issue. All the demos are accompanied by the code needed to reproduce them. What’s the demo you are referring to?

**Comment by AmirTugi** [comment]
None of the demos have the complete code - the html elements and how they are ordered.
For example - [here](https://popper.js.org/) in the overflow prevention, I would like to know how the popper is styled, and how the arrow is disappearing.
Now the code itself, I found out, is stored in [this repo](https://github.com/popperjs/website/blob/master/src/components/Demos.js). So I managed to get the complete demo code.
But it was a bit of a struggle, and I think that as a user, the best experience is that you don't have to be looking for things.

**Comment by FezVrasta** [comment]
Probably it'd be helpful if we organized the demo code so that it can be consumed by CodeSandbox, so that we can add a link to each demo that will automatically generate the example.

I'm not sure I understand the question about the modal overlay.

**Comment by FezVrasta** [comment]
I added a "Edit on CodeSandbox" link below each of the home page examples, hopefully they will be useful.
