### ISSUE TITLE
Flip not working for placement placement: 'bottom-start' popper.js

### ISSUE THREAD

**Issue by ViralVikku** [popperjs/popper-core#1122]
I am using popper.js 1.x, Flip is not working for placement: 'bottom-start' .
Below is the code that i am trying. 
The same code it is working, if I change `placement: 'top-start'`
Can someone please tell, what parameter I am missing or what I need to add again?

And Is there any other property 
```
private readonly popperConfig: PopperOptions = {
        placement: 'bottom-start',
        modifiers: {
            preventOverflow: {
                escapeWithReference: true,
            },
        },
    };
```

**Comment by FezVrasta** [comment]
Hi, if you didn't ignore our issue template you would have read the following:

> Is your issue related to Popper v1? Please consider to migrate to v2, we are not actively
developing previous versions if not for security patches.

Closing, thanks!

**Comment by ViralVikku** [comment]
@FezVrasta Is the above mentioned issue fixes in version 2?
