### ISSUE TITLE
Popper will not set its placement immediate after click

### ISSUE THREAD

**Issue by ViralVikku** [popperjs/popper-core#1126]
Please check the below GIF, I have used Popper.js latest v.2.x but Popper will not immediately place to its position in the first click, I need to scroll to get it updated...  Below is the code I am using
Am I missing any parameter?
```
const options = {
strategy: 'fixed',
        placement: 'bottom-start',
        modifiers: [
            {
                name: 'preventOverflow',
                enabled: true,
                options: {
                    escapeWithReference: true,
                },
           {
                name: 'flip',
                options: {
                    enabled: true,
                    fallbackPlacements: ['top', 'bottom'],
                    allowedAutoPlacements: ['top', 'bottom'],
                },
            },
            },
        ],
}
this.popperInstance = createPopper(
                this.dropDownButton.nativeElement as HTMLElement,
                this.dropDownMenu.nativeElement as HTMLElement,
                options
            ); 
```
![ezgif-3-58978a648b67](https://user-images.githubusercontent.com/66131205/83965851-3d1c0100-a8d4-11ea-847e-56e0129d35f5.gif)

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
