### ISSUE TITLE
Hide is always true beneath the initial height of the screen.

### ISSUE THREAD

**Issue by skvale** [popperjs/popper-core#1127]
### CodeSandbox demo

https://codesandbox.io/s/naughty-chandrasekhar-tntlb?file=/index.html

### Steps to reproduce the problem

![hidden-popper](https://user-images.githubusercontent.com/5314713/84065580-3354d500-a98a-11ea-9173-bf2009c40c7d.gif)

### What is the expected behavior?

The poppers are the same in the example.

Poppers beneath the initial height of the screen should not always be hidden.

### What went wrong?

Adding `overflow-y: hidden` to the html tag works.  But I noticed this breaks how `window.pageYOffset` works.  So I don't see that as a fix.

### Any other comments?

Changing to earlier versions of popper can fix this issue, like `v2.3.3`

**Comment by atomiks** [comment]
Is this code the issue? https://github.com/popperjs/popper-core/compare/v2.3.3...v2.4.0#diff-b5083dda8e7f88fca4b4d0ea0ef3b683R25-R28

**Comment by atomiks** [comment]
Looks like it's caused by `overflow-y: scroll` on the `<body>` - removing that property fixes the issue, is there a reason why you have that property? In fact that fix we added was for an esoteric case with an `overflow-y: scroll` `<body>` but `overflow-y: hidden` `<html>`...
