### ISSUE TITLE
Infinite loop if popper is an unmounted element

### ISSUE THREAD

**Issue by AlbertLucianto** [popperjs/popper-core#1128]
### CodeSandbox demo

https://codesandbox.io/s/adoring-meadow-jq7i8

### Steps to reproduce the problem

1. Create an element that's not mounted
2. Set it as popper element

### What is the expected behavior?

Does nothing (before v2.4.1), or maybe a warning can be given.

### What went wrong?

Stuck in infinite loop.

### Any other comments?

I have checked and I think the code causing the problem is in [these lines](https://github.com/popperjs/popper-core/blob/master/src/dom-utils/getOffsetParent.js#L26). When an unmounted element is given to `getParentNode(el)` it returns the root html. Then when html element is given to `isHTMLElement(el)` it will be `false` and cause infinite loop.

I used react-popper, and I think it's not uncommon to have popper element that suddenly gets unmounted.

Doesn't have the problem in v2.4.0.

**Comment by rijkvanzanten** [comment]
I can confirm I'm seeing the same behavior on my end in a Vue based application
