### ISSUE TITLE
detectOverflow util not exported on '@popperjs/core'

### ISSUE THREAD

**Issue by lainermeister** [popperjs/popper-core#1130]
![Screen Shot 2020-06-15 at 3 42 56 PM](https://user-images.githubusercontent.com/26628913/84699526-aa0c4800-af1f-11ea-9d6a-8989a7f60dbb.png)

### Steps to reproduce the problem

1. `yarn add @popper/core`
2. In component file, write `import { detectOverflow } from '@popperjs/core';`
3. Get module not found error.

### What is the expected behavior?

As describe in [the docs](https://popper.js.org/docs/v2/utils/detect-overflow/), `detectOverflow` should be able to be imported as a util from `@popperjs/core`.
### What went wrong?

I received an error saying there was no exported member `detectOverflow`.

### Any other comments?

I'm using ` "@popperjs/core": "^2.4.2",` I do not see `detectOverflow` as one of the exported members in `./lib`.

**Comment by atomiks** [comment]
[It is exported](https://unpkg.com/browse/@popperjs/core@2.4.2/lib/popper.js) (see bottom)

**Comment by lainermeister** [comment]
Interesting...how do you explain the error I am getting then? Am I importing from the wrong module path?

**Comment by lainermeister** [comment]
@atomiks @FezVrasta It seems like `@popperjs/core` does not have the same exports as `@popperjs/core/lib/popper.js` (which is the link you sent).

`@popperjs/core` exports from `./lib` https://unpkg.com/browse/@popperjs/core@2.4.2/index.d.ts

...which in turn imports a set of functions, types, and enums that do not include `detectOverflow`
https://unpkg.com/browse/@popperjs/core@2.4.2/lib/index.d.ts

Is the correct import `import { detectOverflow } from '@popperjs/core/lib/popper';`? That is different from the docs say.

**Comment by SankalpaHettiarachchi** [comment]
1. Move these file from node_modules\@popperjs\core\lib\utils to E:\Github\DevCada\node_modules\@popperjs\core\lib

    - detectOverflow.d.ts
    - detectOverflow.js
    - detectOverflow.js.flow
    
2. Restart the server 
    > npm start
