### ISSUE TITLE
preventOverflow should allow root boundaries to be set to `window`

### ISSUE THREAD

**Issue by AndrewOCC** [popperjs/popper-core#1131]
## Feature description

One use case for the preventOverflow modifier would be to allow the popper to be constrained to the boundaries of the window. When the user is zoomed in at high magnifications (200/400%) or has reduced their viewport size, the window may extend past the edge of the viewport; the requested behaviour would allow the user to move the viewport around the window without the popper 'following' them.

Currently in popper v2, rootBoundary can only be set to `viewport` or `document`. `rootBoundary: 'document'` isn't helpful for this case, as at high zoom levels the document boundaries are a viewport-sized bounding box in the top left of the page, so a reference elements sitting outside of the document boundary are positioned as if the reference is off-screen. With rootBoundary set to `viewport` the popper will stick to the edges of the viewport as you scroll around; a big enough popup may obscure large parts of the screen until the reference is completely off-screen.

An example for experimenting with this behaviour in popper v2 is in this codesandbox: https://codesandbox.io/s/small-hill-lpc3i?file=/src/index.js 
Zoom in so that the reference element is partially out of the viewport on load, and move around. There doesn't appear to be a configuration of preventOverflow that allows the popper to sit directly below the reference and not shift to sit the boundaries of the viewport or document, without disabling preventOverflow entirely and losing overflow prevention on the edges of the window.

This behaviour was supported in popper v1 via the boundariesElement option:
https://codesandbox.io/s/holy-wood-jmw9u?file=/src/index.js

## Why should this feature be part of the Popper's core?

Allowing the popper to behave independently of the viewport at high zoom settings or viewport positions is useful as it can allow the user to scroll around a page without the popper 'following them', while also keeping the popper from overflowing the window and being partially obscured.

This makes sense as core behaviour as it's restoring functionality to a core modifier, `preventOverflow`, and that modifier has a rootBoundary option where this option could logically be added (similar to boundariesObject in popper v1)

**Comment by atomiks** [comment]
This is fixed in `v2.4.2`, if you update the version in the CSB it appears to work

**Comment by AndrewOCC** [comment]
Oh that's great news, thanks for the quick response 😄 
Follow-up question (I can raise a ticket around it if it's not supported); is there a way to allow `hide` to only occur when the popper leaves the window?

**Comment by atomiks** [comment]
I don't think so; I think it should allow all the `detectOverflow` options to be passed though. You can create a custom modifier to add the functionality yourself tho

**Comment by AndrewOCC** [comment]
Thanks for the help, I'll mark this as resolved then
