### ISSUE TITLE
Wrong position when creating popover with setTimeout

### ISSUE THREAD

**Issue by lomm28** [popperjs/popper-core#1132]
### CodeSandbox demo

https://codesandbox.io/s/quizzical-hypatia-dbegh

### Steps to reproduce the problem

1. Upon the initial component render, when you hover over the reference element the tooltip is incorrectly positioned.
2. If you hover again, there seems to be no issues.
3. Works just fine if you don't wrap popper initialization in setTimeout.

### What is the expected behavior?

The tooltip should appear in the correct position.

### What went wrong?

Tooltip seems to be off when you hover over the reference element for the first time.

**Comment by FezVrasta** [comment]
Consider to use react-popper instead, it will make easier the integration with you code. The bug doesn’t seem related to Popper
