### ISSUE TITLE
Add extension ability to the tooltip.

### ISSUE THREAD

**Issue by NemoDima** [popperjs/popper-core#1135]
## Feature description

For the Popper 1.X/2.X could you Add extension ability to the tooltip, please?

This would be useful for a tooltip that I would not want to display all at once, but it should be shown completely at the request(click) of the user.

![изображение](https://user-images.githubusercontent.com/43349820/85221940-8d10c280-b3c0-11ea-835b-76970de2cc35.png)

## Why should this feature be part of the Popper's core?

Because the Popper library can add one more interesting option for the tooltip.

Thanks!

**Comment by FezVrasta** [comment]
Please take a look at Tippy. Popper is not a tooltip library
