### ISSUE TITLE
Fixed strategy works strange with Chrome and Safari navbar on mobiles

### ISSUE THREAD

**Issue by dimitriirybakov** [popperjs/popper-core#1136]
### CodeSandbox demo

https://codesandbox.io/s/tender-oskar-s94e6

### Steps to reproduce the problem

![video_2020-06-23_11-16-33](https://user-images.githubusercontent.com/16699909/85378341-1bad4d00-b543-11ea-9f59-f7771af75e1c.gif)

1. Open sandbox on mobile in Chrome
2. Scroll down when Chrome's navbar is hiding.
3. See that popup's position is changing.

### What is the expected behavior?

Popup's position shouldn't change.

### What went wrong?

Poper overlaps with reference without any reason

**Comment by atomiks** [comment]
Does it happen if you use `rootBoundary: "document"` instead of `"viewport"` (updated to `v2.4.2`)?

**Comment by dimitriirybakov** [comment]
@atomiks thanks for your reply! I've added `flip` and `preventOverflow` but it changed nothing. https://codesandbox.io/s/tender-oskar-s94e6
Maybe I didn't understand you right?

**Comment by atomiks** [comment]
That's right but the CSBX still says `v2.4.0`, it should be `v2.4.2`

**Comment by dimitriirybakov** [comment]
Yep, sorry, update it. Still no effect.

**Comment by dimitriirybakov** [comment]
@atomiks maybe you have any other recommendations? :)

**Comment by atomiks** [comment]
Sorry I don't; you'll need to clone the repo and start debugging this yourself as I can't test it easily. It's likely related to `getViewportRect` / `getClippingRect` if you want to investigate.
