### ISSUE TITLE
Package's "module" should use dist ES build

### ISSUE THREAD

**Issue by dasa** [popperjs/popper-core#1137]
https://github.com/popperjs/popper-core/blob/38914aae7a2e91715c6eb2b563517082a40cfa64/package.json#L7

Should this be "dist/esm/popper.js"?

**Comment by atomiks** [comment]
`dist/esm/popper.js` is the same as `lib/popper.js` except without development checks

**Comment by dasa** [comment]
The error I'm getting is:

```
index.js:80 Uncaught ReferenceError: process is not defined
    at Object.setOptions (index.js:80)
    at createPopper (index.js:214)
```

I'm testing with [es-dev-server](https://github.com/open-wc/open-wc/tree/master/packages/es-dev-server). My import is `import { createPopper } from "@popperjs/core";`.

I can workaround it by using `import { createPopper } from "@popperjs/core/dist/esm/popper";`, but it'd be nice if I didn't have to.

Would you accept a PR with this change?

**Comment by FezVrasta** [comment]
`lib/popper.js` **is** an ES build already, please read the docs, they explain the different dist targets.

**Comment by nenadvicentic** [comment]
@FezVrasta Sorry, but I don't understand something here: 

> `lib/popper.js` **is** an ES build already, please read the docs, they explain the different dist targets.

Your documentation states:

> There are two different esm builds, one for bundler consumers (e.g. webpack, Rollup, etc..), which is located under /lib, and one for browsers with native support for ES Modules, under /dist/esm. The only difference within the two, is that the browser-compatible version doesn't make use of process.env.NODE_ENV to run development checks.

However, this is not correct. Your `dist/lib` contains js files that are using `process.env`. `process` is NodeJS object [here](https://nodejs.org/api/process.html#processenv) and thus using `process.env` throws exception in a browser.

In more details:

Your `dist/lib/popper.js` contains imports and exports from other files. However, one of the imports in that file is:
```js
import { popperGenerator, detectOverflow } from "./createPopper.js";
```

The file `createPopper.js` contains multiple checks of `process.env.NODE_ENV`:
```js
if (process.env.NODE_ENV !== "production") {
          var modifiers = uniqueBy([].concat(orderedModifiers, state.options.modifiers), function (_ref) {
            var name = _ref.name;
            return name;
          });
```
This in turn breaks in a browser:

```batch
Uncaught ReferenceError: process is not defined
    at Object.setOptions (createPopper.js:82:1)
    at Object.createPopper (createPopper.js:200:1)
    at Dropdown._createPopper (bootstrap.esm.js:1800:1)
    at Dropdown.show (bootstrap.esm.js:1720:1)
    at Dropdown.toggle (bootstrap.esm.js:1707:1)
    at HTMLAnchorElement.<anonymous> (bootstrap.esm.js:1963:1)
    at HTMLDocument.handler (bootstrap.esm.js:334:1)
 ```

**Comment by FezVrasta** [comment]
> There are two different esm builds

Two builds, different from each other.

> one for bundler consumers (e.g. webpack, Rollup, etc..), which is located under /lib

One, designed to be used with webpack & co, you can find it at `/lib`

> and one for browsers with native support for ES Modules, under /dist/esm.

One, designed to be used in browsers, at `/dist/esm`

So when you say:

> Your lib contains js files that are using process.env. process is NodeJS object [here](https://nodejs.org/api/process.html#processenv) and thus using process.env throws exception in a browser.

Did you actually read the docs first?

**Comment by FezVrasta** [comment]
Unfortunately we don't have any control over Bootstrap, it's up to them to import the correct targets.

For the TypeScript issue, supporting a more straightforward approach would be a huge undertake and a breaking change, I would advise to switch to Floating UI since everything works by default on it.

**Comment by nenadvicentic** [comment]
`bootstrap` , as a workaround, publishes `bootstrap.bundle` version which bakes `popper` inside and avoids above issues.

Problem is when I need to use unbundled bootstrap (because bundle does not have of exports):
```js
import { Toast } from `bootstrap`;
```
It, correctly has dependency to:
```js
import { createPopper } from "@popper/core";
```
And then again it get's wrongly resolved to NodeJS version, not web.

I doubt that you would be able to bypass this kind of limitation if `Floating UI`.

**Comment by FezVrasta** [comment]
AFAIK with Floating UI we are using ES module exports maps to fix this issue. But it's something we couldn't add to Popper for backward compatibility issues.

You may always set an alias in webpack or rollup to point any popper import to the correct target.

**Comment by nenadvicentic** [comment]
@FezVrasta  Thank you! I checked if I could set alias with `aurelia-cli` that I am using.

Adding redirect to `dependencies` the standard section of `aurelia.json` file solved the issue:

```json
"dependencies": [
    "aurelia-bootstrapper",
    "aurelia-loader-default",
    "aurelia-pal-browser",
    {
    "name": "aurelia-testing",
    "env": "dev"
    },
    {
    "name": "@popperjs/core",
    "path": "../node_modules/@popperjs/core",
    "main": "dist/esm/index.js"
    },
    "text"
]
```
