### ISSUE TITLE
html {position: relative} breaks adaptive positioning with strategy "absolute"

### ISSUE THREAD

**Issue by diondiondion** [popperjs/popper-core#1138]
### CodeSandbox demo

https://codesandbox.io/s/immutable-rgb-i2bxu?file=/src/index.js

### Screencap

![disappearing-tooltip](https://user-images.githubusercontent.com/5636050/85689104-a40e2800-b6d2-11ea-92c0-a8f2fbde31a2.gif)

### Steps to reproduce the problem

1. Apply `position: relative` to the document's root/html element
2. Create a popper with `placement: 'bottom'` and the default `strategy: 'absolute'` and adaptive positioning
3. Scroll the page so that the reference element gets close to the bottom border of the viewport

### What is the expected behavior?

The popper should stay attached to the reference as it flips to the top edge of the reference

### What went wrong?

The popper is misplaced (disappears outside of view) when the adaptive "flip to top" behaviour is triggered

### Any other comments?

- This may be related to, but isn't the same as #1114. This happens in all browsers I have access to (Chrome, Safari, Firefox, Edge).
- Disabling adaptive positioning or using `strategy: 'fixed'` will prevent this issue from happening, however especially adaptive positioning is extremely useful for the use case of dropdown menus which is especially affected by this bug.

**Comment by atomiks** [comment]
It seems like the popper disappears from the document entirely in this case... I tried to position in view but couldn't find where it even was. Simple fix: add `position: relative` to `<body>` also.

**Comment by diondiondion** [comment]
> It seems like the popper disappears from the document entirely in this case... 

It's still there, at the very bottom of the page, as that's what it's being positioning from. It's just using the wrong offset (`bottom: 0` instead of the approximately 600 pixels needed to position it correctly in the demo).

> Simple fix: add `position: relative` to `<body>` also.

I wish it was that simple for us, unfortunately for us that breaks various other styling aspects of our app. (i.e. the modals for which some crazy things have to be done to prevent scrolling of the page behind them on Safari iOS...)

So, yeah... would be much appreciated if this could be fixed in the library if possible.

**Comment by atomiks** [comment]
But it seems to only work with `bottom: 600px`, gpuAccleration `bottom: 0` + `transform: translate3d(0, 600px, 0)` doesn't make it appear... 🤔 

Also why `html { position: relative }` in the first place?

**Comment by diondiondion** [comment]
> But why `html { position: relative }` in the first place?

It's the only robust way (that I know of) to allow an absolutely positioned element (think semi-transparent modal backdrop) to take up the whole height of a scrollable page. Without it, the element won't extend past the height of the initial viewport.

However it seems like moving `{position: relative}` to the `body` keeps that use case working.

**Comment by diondiondion** [comment]
Hi @atomiks , thanks so much for addressing this issue so quickly. I only got around to verifying #1141 now and it looks like that PR didn't fix it – the popper now scrolls along with the page. (See [here](https://user-images.githubusercontent.com/5636050/86792583-ef2d2100-c06a-11ea-9662-dac2659b3be8.gif) for a screen capture of the [same reproduction demo with updated dependency](https://codesandbox.io/s/immutable-rgb-i2bxu?file=/src/index.js) in case it's still relevant.)

However it looks like you noticed yourself – I just tried your latest code from the new PR #1148 and that seems to be working fine in both Chrome and Firefox for me, even though the reproduction demo isn't exactly the same. (Is there a way to use a PR branch like that in Codesandbox, without cloning the repo to my local machine? Would make verifying PRs much easier.
Tried `"dependencies": {"@popperjs/core": "https://github.com/atomiks/popper.js.git#fix/relative-html-2"}`, but that's not working, I guess it's missing the compilation. If there's a trick to make it work that would be much appreciated.)

**Comment by vincerubinetti** [comment]
It seems like this issue really needs to be reopened.

I'm having a [similar problem](https://github.com/popperjs/react-popper/issues/383), except that I'm not using `position: relative` at all. Here is the test case:

[test.zip](https://github.com/popperjs/popper-core/files/5081022/test.zip) (run `yarn install && yarn start`)

![oR8QhEri51](https://user-images.githubusercontent.com/8326331/90339363-499c9400-dfbe-11ea-8c0b-62b9bc50cdcd.gif)

**Comment by vincerubinetti** [comment]
Hi is there any update on this? This should probably be reopened. It seems to still be in the latest version, which is concerning. Not sure how more people aren't running into this issue, or how it wasn't caught. It literally comes up with the most basic use of the upstream `tippy` and `react-popper` libraries.

**Comment by happylolonly** [comment]
@FezVrasta it is still not working correct, need to reopen.
for me also only `stategy: fixed` fixing it

https://github.com/mohsinulhaq/react-popper-tooltip/issues/167
