### ISSUE TITLE
Popper positioning (strategy = 'fixed') broken in ie11

### ISSUE THREAD

**Issue by AndrewOCC** [popperjs/popper-core#1145]
### CodeSandbox demo

ie11 doesn't support CodeSandbox, but here's a JSBin that shows the same issue:
https://jsbin.com/nakizamosi/1/edit

### Steps to reproduce the problem

1. Create a popper example using either `@popperjs/core` or `react-popper` that sets `strategy = 'fixed'`.
2. View in IE11
3. Popper will not position correctly

### What is the expected behavior?

The popper should position in a similar fashion to other browsers

### What went wrong?

When using `strategy: 'fixed'` the popper appears in the wrong spot on the page – as if it is offset by some large number of pixels. Flipping and hiding appears to work, but not positioning. `strategy: 'absolute'` works fine. The error only seems to occur when the reference/popper are wrapped in some other element, like the wrapping div in the example above.

### Any other comments?

As this is a major regression for ie11, if the issue is a 'won't fix' it would be useful to add a warning to the upgrade guide that ie11 support for `position: fixed` has been dropped or has rendering issues.

**Comment by atomiks** [comment]
https://github.com/popperjs/popper-core/pull/1139

**Comment by skorzyk** [comment]
Same problem here, when can I expect the patch version?

**Comment by wszydlak** [comment]
Hi any updates with this? When new version is planned to be released? We are waiting for our application release for this issue to be fixed.

**Comment by atomiks** [comment]
You can downgrade your version with it locked to `2.4.0` while awaiting a patch for this (`v2.4.1` broke it) 

Remember we can't/won't test IE11 so things can break between patches like this. [See docs on IE11 support](https://popper.js.org/docs/v2/browser-support/#support-note). If you need to support IE11 you should lock your version and test each patch for IE11 support instead of allowing every update (`^` version range)

**Comment by wszydlak** [comment]
But version 2.4.0 has not working fixed strategy with containing blocks. I need both fixed with containing blocks and this issue resolved. That's why i'm asking if we can expect from you to release new version this week?
