### ISSUE TITLE
Problem with `data-popper-escaped` and `overflow: hidden` button reference

### ISSUE THREAD

**Issue by majkel100** [popperjs/popper-core#1146]
### CodeSandbox demo

https://codesandbox.io/s/wonderful-hellman-hg1p2

### Steps to reproduce the problem

1. Create button with `ovrflow: hidden` style
2. Add `visibility: hidden` to [data-popper-escaped]

### What is the expected behavior?

I expect tooltip to display when `strategy: fixed`

### What went wrong?

Popper set `data-popper-escaped` on reference element even it's full viewed.

### Any other comments?

I use some fancy animations on buttons, so i need to use `overflow: hidden` on them. I use data-popper-escaped to hide popper element when scrolling content. Any idea how to prevent this behavior?  I

Popper version 2.4.3

Browser: Chrome, Firefox and probably others

**Comment by atomiks** [comment]
Maybe you need to make the reference a wrapper element of the button as a workaround. But it looks like a bug when the reference element has `overflow: hidden` on it. It's present on v2.2.0 so it seems like a longstanding bug and not a recent regression.

**Comment by wszydlak** [comment]
Yeah, I had same issue, PR You submitted fixed it. Can we expect some release today?

**Comment by ptu14** [comment]
@majkel100 I noticed it some time ago, but I didn't report this as a bug, I just wrap reference item with `display: inline-block` span. Nice that you fix it @atomiks. 

When you plan release next version? I release the version of my product and it would be nice to have it working.
