### ISSUE TITLE
Align popper in the middle/center doesn't work

### ISSUE THREAD

**Issue by hzrcan** [popperjs/popper-core#1154]
I want to align the popper in the center of the top like:

![example_popper](https://user-images.githubusercontent.com/3510239/88641537-a8f23d00-d0bf-11ea-895b-69d3f6802f30.png)

But what I get is:

![2020-07-28 10_41_34-popper](https://user-images.githubusercontent.com/3510239/88641577-b4456880-d0bf-11ea-9d0b-e746b4aab9bc.png)

So the popper needs to be aligned in the center of the top instead of right and the arrow needs to be aligned in the center. It aligns correct when I scroll on the page. But not on the first loading.

My settings for the propper:
`const button = document.getElementById('i-text-button-' + this.element.id) as any;`
`const popper = document.getElementById('popper-' + this.element.id) as any;`
`const arrow = document.getElementById('arrow' + this.element.id) as any;`

`createPopper(button, popper, {
    placement: 'top',
    strategy: 'fixed',
    modifiers: [
        {
            name: 'arrow',
            options: {
                element: arrow,
            }
        },
        {
            name: 'offset',
            options: {
                offset: [-20, 15],
            }
        },
        {
            name: 'computeStyles',
            options: {
                gpuAcceleration: false, // true by default
            },
        }
    ],
});`

This works in the old version of popper.js. I have followed the migration document but am not getting it working as desired.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
