### ISSUE TITLE
2.x regression from 1.x - cannot pass detached Node as popper

### ISSUE THREAD

**Issue by pretzelhammer** [popperjs/popper-core#1155]
According [to this PR](https://github.com/popperjs/popper-core/pull/28) it was possible to pass a popper node to `createPopper` that was detached from the DOM. It was also possible to pass text or HTML content as a string. Why is this no longer supported in 2.x?

### Codepen demo

https://codepen.io/kfedorov91/pen/WNrBgZR

### Steps to reproduce the problem

1. visit [codepen link](https://codepen.io/kfedorov91/pen/WNrBgZR) above
2. open devtools console

### What is the expected behavior?

I expect `createPopper` to work when I pass it some popper node, regardless of whether that node is attached the DOM or not.

### What went wrong?

```
Uncaught TypeError: Cannot read property 'documentElement' of undefined
    at getDocumentElement (getDocumentElement.js:10)
    at getParentNode (getParentNode.js:17)
    at getScrollParent (getScrollParent.js:17)
    at getScrollParent (getScrollParent.js:17)
    at listScrollParents (listScrollParents.js:19)
    at Object.setOptions (index.js:95)
    at Object.createPopper (index.js:261)
    at pen.js:9
```

### Any other comments?

As stated above this was [reported in 2016](https://github.com/popperjs/popper-core/issues/27) and [fixed in 2016](https://github.com/popperjs/popper-core/pull/28) but no longer works in 2.x.

**Comment by FezVrasta** [comment]
That was a functionality related to Tooltip.js, not about Popper.
