### ISSUE TITLE
DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by dsujoy** [popperjs/popper-core#1160]
I'm calling the script in a laravel project from 

<script src="https://unpkg.com/@popperjs/core@2"></script>

I'm getting the following error msg from the chrome console.

DevTools failed to load SourceMap: Could not load content for https://unpkg.com/@popperjs/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Thomaasss** [comment]
same problem !

**Comment by tiec7** [comment]
Same for me

**Comment by Nastaran28** [comment]
same here!
