### ISSUE TITLE
Using popperjs-lite breaks bundling behavior

### ISSUE THREAD

**Issue by hipstersmoothie** [popperjs/popper-core#1161]
### Steps to reproduce the problem

My team runs a design system for use in other apps. All of our components have `module` and `main` set up so that when you import our component the consumer's bundler can decide on what code to use.

Recently we switched from the main `createPopper` to the `createPopper` from `@popperjs/core/lib/popper-lite`. But now that this import path goes directly to ESM code, bundlers can't choose the right `popper-lite` to bundle with. This has led to consumers of our component to have to edit their webpack builds to whitelist popperjs as a `node_module` to build.

This behavior carries a lot of friction.

### What is the expected behavior?

I can use `popper-lite` without directly accessing any particular file.

### Any other comments?

My solution for this is pretty simple, only requires a little bit of restructuring, and is not a breaking change.

1. Move all code from `src/index.js` to `src/createPopper.js`
2. Make `src/index.js` contain only export statements

```js
export type * from './types';
export * from './enums';
export * from './createPopper';
export { createPopper as createPopperLite } from './popper-lite';
```

3. Change all docs to suggest importing from

```js
import { createPopper } from "@popperjs/core/lib/popper-lite";
```

to

```js
import { createPopperLite as createPopper } from "@popperjs/core";
```

Now since consumers of `@popperjs/core` aren't importing a built file bundlers can choose the correct file.

**Comment by hipstersmoothie** [comment]
I am willing to contribute this code. Just running my idea by the maintainers before going ahead with implementation.

**Comment by hipstersmoothie** [comment]
Ah we would need to do something similar with modifiers too

**Comment by mkarachev** [comment]
Hi there! Any updates on this issue? As i can see, pr was opened about month ago. Maybe you need help or something?

**Comment by hipstersmoothie** [comment]
PR is up and it works. I published the work under my user scope and it's been working well. Feel free to install and report any issue you have here 

https://www.npmjs.com/package/@alisowski/popperjs-core
