### ISSUE TITLE
Allow positioning against a Range

### ISSUE THREAD

**Issue by kamilmielnik** [popperjs/popper-core#1168]
## Feature description

Allow positioning against a [`Range`](https://developer.mozilla.org/en-US/docs/Web/API/range).
Currently only positioning against a `Element` or `VirtualElement` is possible: https://github.com/popperjs/popper-core/blob/b34157e380c0d3ae0a4fa3fc94ca25928761fa60/src/index.js#L57

## Why should this feature be part of the Popper's core?

`Range` does not correspond to a single `Element` or `VirtualElement`, so it's not possible to use Popper for positioning against a `Range` with the current API. 

### Use case
Positioning a floating formatting menu near text selection ([window.getSelection()](https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection)[.getRangeAt(0)](https://developer.mozilla.org/en-US/docs/Web/API/Selection/getRangeAt) returns `Range`) in rich text editors (using [contenteditable](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/contentEditable)) such as [Slate](https://www.slatejs.org).

![image](https://user-images.githubusercontent.com/6830683/92587946-8bb9ac80-f2c2-11ea-879f-4f933dd765e7.png)

**Comment by FezVrasta** [comment]
Why can't you use a VirtualElement instead? I do that with Slate and it works wounderfuly.

**Comment by kamilmielnik** [comment]
@FezVrasta I totally can :man_facepalming: , thank you!

**Comment by wong2** [comment]
@kamilmielnik @FezVrasta Is there an example of using VirtualElement for text selection?
