### ISSUE TITLE
Popper is not correctly placed

### ISSUE THREAD

**Issue by piecyk** [popperjs/popper-core#1169]
### CodeSandbox demo

https://codesandbox.io/s/elated-sid-sgwqg ( refresh codesandbox embedded browser )  

### Steps to reproduce the problem

No steps required, popper is not correctly placed 

<img width="682" alt="Screenshot 2020-09-09 at 16 23 30" src="https://user-images.githubusercontent.com/82964/92611187-d2a2a480-f2b8-11ea-95bd-c33e2eb5c5dc.png">

### What is the expected behavior?

Popper should be correctly placed 

### What went wrong?

Looks like in flex box container, if element before has some non integer width ( as in this example using content editable `aaas` has width of `27.531` ) popperjs fails to correctly place the popper  

### Any other comments?

Looks like it's connected with #713

**Comment by davoam** [comment]
I found that it happens if `getBoundingClientRect` returns not integer `left` value for the trigger element (e.g. `31.5 px`). In this case popper position is less by 1px from proper one. In my case it happens only when `fixed` strategy is used.

**Comment by piecyk** [comment]
Also one possible workaround is to change display of anchor element to `inline-table` That would make element to render width/height as integers, so we don't get sub-pixels.

**Comment by piecyk** [comment]
Thinking on it, why we need the rounding at all ? Looking on modern browser all would handle it 🤔 Maybe given option to opt out from rounding would be not that bad idea? WDYT?

**Comment by piecyk** [comment]
So something like this https://github.com/popperjs/popper-core/compare/master...piecyk:feat/round-option With `round: false` user can opt out from rounding. 

```
{
  name: 'popperOffsets',
  options: {
    round: false,
  },
},
```

Tested on firefox, safari, edge and looks great with pixel perfect position of popper. On chrome looks like there is a bug setting position with `translate3d/translate` makes it not correctly placed, but using left/top it is. IMHO there should be no difference. Need to check if someone reported a bug. Till then we need to fallback to left/top with disabling gpuAcceleration on `computeStyles`

**Comment by piecyk** [comment]
Example of those inaccuracies in chrome/edge between position `left/top` vs `translate3d/translate` what i was writing above  https://codesandbox.io/s/cool-chandrasekhar-mcbp1
