### ISSUE TITLE
Documentation of Parameters for onFirstUpdate

### ISSUE THREAD

**Issue by janhaertel** [popperjs/popper-core#1171]
Hi is there a **documentation** for the **parameters** of **onFirstUpdate** ?
I was only able to find the options I can use by debugging the function, which is unpractically.

**Comment by FezVrasta** [comment]
[`onFirstUpdate` docs](https://popper.js.org/docs/v2/lifecycle/#hook-into-the-lifecycle) and [`State` type](https://github.com/popperjs/popper-core/blob/777ebbbacb590e582b90c2b0c81e14653e278914/src/types.js#L76-L115)
