### ISSUE TITLE
@popperjs/core: Command failed

### ISSUE THREAD

**Issue by afuno** [popperjs/popper-core#1176]
yarn 1.22.5

---

I update packages every day with this command:

```
yarn upgrade
```

But today I got a problem.

As before, I tried to update packages. I ran the command I showed above. As a result, I got this:

```
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has unmet peer dependency "webpack@^4.0.0".
[4/4] 🔨  Building fresh packages...
[1/5] ⠂ @popperjs/core
[2/5] ⠂ fsevents
[3/5] ⠂ core-js
[4/5] ⠂ node-sass
error /Users/afuno/app1/node_modules/@popperjs/core: Command failed.
Exit code: 127
Command: patch-package
Arguments:
Directory: /Users/afuno/app1/node_modules/@popperjs/core
```

I deleted the yarn.lock file and node_modules directory. And then I ran this command:

```
yarn install
```

And it didn't help.

**Comment by afuno** [comment]
I removed the `@popperjs/core` line from the package.json file. And `yarn` started to install and update successfully.

Then I tried to execute this command:

```
yarn add @popperjs/core
```

And got the error I showed in the first post.

**Comment by angelblanco** [comment]
Got the same error here

**Comment by afuno** [comment]
I saw that you released 30 minutes ago. The problem is related to this release. Using fixed version 2.4.4 is successful.

**Comment by webgefrickel** [comment]
Same here: v2.5.0 is breaking the install/upga:

```
❯ npm install @popperjs/core

> @popperjs/core@2.5.0 postinstall ~/Downloads/poppertest/node_modules/@popperjs/core
> patch-package

sh: patch-package: command not found
npm WARN poppertest@1.0.0 No description
npm WARN poppertest@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @popperjs/core@2.5.0 postinstall: `patch-package`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @popperjs/core@2.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by FezVrasta** [comment]
2.5.1 should fix it, it will be available in a few minutes

**Comment by afuno** [comment]
@FezVrasta Thanks for your promptness

**Comment by FezVrasta** [comment]
May someone confirm it's working?

**Comment by afuno** [comment]
@FezVrasta In version 2.5.1 everything is successful.
