### ISSUE TITLE
Removal of DOM element not recognised by popper

### ISSUE THREAD

**Issue by smollweide** [popperjs/popper-core#1178]
### CodeSandbox demo

https://codesandbox.io/s/elated-galois-8nvfs

### Steps to reproduce the problem

1. Click on the button "x"
2. Tooltip stays on the old position

![Screencast](https://user-images.githubusercontent.com/2912007/95168877-4483e600-07b2-11eb-975c-e1963d1f2ad7.gif)

### What is the expected behavior?

The tooltip should be positioned at the same position as before.

**Comment by FezVrasta** [comment]
We don't track DOM mutations, it's the consumer responsibility to update the position when the DOM changes.
