### ISSUE TITLE
The offset modifier is not working well with Angular

### ISSUE THREAD

**Issue by maykon-oliveira** [popperjs/popper-core#1181]
### CodeSandbox demo

https://stackblitz.com/edit/popperjscore?file=src/app/app.component.ts

### Steps to reproduce the problem

1. Install dependency
2. Write a simple component following doc example
3. Use `offset` modifier

### What is the expected behavior?

The tooltip div should be 10px of distance from button.

### What went wrong?

No matter what value you set there, the tooltip is always together with button.

### Any other comments?

Arrow modifier not works too

**Comment by wjaspers** [comment]
The documentation is a little misleading.
You need to include the `offset` modifier and provide the `offset` configuration.
See https://stackblitz.com/edit/popperjscore-cqozkj?file=src/app/app.component.ts
