### ISSUE TITLE
Margin-styling lingers on element after popper instance is destroyed

### ISSUE THREAD

**Issue by RonaldTreur** [popperjs/popper-core#1182]
### CodeSandbox demo

https://codesandbox.io/s/popper-margin-lingering-myytz

### Steps to reproduce the problem

1. Open CodeSandbox link
2. Click toggle-button ("show) in renderer (notice the popup is empty so nothing will be shown)
3. Click toggle-button ("hide") again

### What is the expected behavior?

My expectation is that the element that was used as popup would have been stripped of all element styling after the Popper instance was destroyed.

### What went wrong?

`margin`-styling lingered on the popup-element

### Any other comments?

This might not seem that important to most, I understand. I happen to work on a project where an element will be shown with Popper when the user's view-size is below a certain threshold. Bigger view-sizes will show a different behavior. The view size can be changed by the user, and this means that both options can occur relatively easily.

So far my own brief research led me to `modifiers/applyStyles.js`. The `effect`-function sets the margin-styling as part of the `initialStyles`, but the cleanup-function it returns will take the style defined in `state.styles.popper` to decide which styles to cleanup. This one lacks the `margin`-style for some reason.

**Comment by atomiks** [comment]
https://github.com/popperjs/popper-core/blob/7cfd52de6fd1771bf8f772c8c21f25a212ff5b1a/src/modifiers/applyStyles.js#L43

In the cleanup function below, it should use that property and set it to an empty string `""`, if you want to investigate, the problem will be in that function alone

**Comment by RonaldTreur** [comment]
Yep @atomiks, that is exactly what I mentioned. The issue is that the styles created over here:
https://github.com/popperjs/popper-core/blob/7cfd52de6fd1771bf8f772c8c21f25a212ff5b1a/src/modifiers/computeStyles.js#L98-L110

don't seem to be setting any margin. Which means that the cleanup function will never clean it up either, since it will select that styling over the initial one (that set the `margin: 0`):
https://github.com/popperjs/popper-core/blob/7cfd52de6fd1771bf8f772c8c21f25a212ff5b1a/src/modifiers/applyStyles.js#L64

I have the strong impression this line is redundant and should be removed. My own testing seems to back this up, but perhaps there is some code somewhere that somehow needs this?
https://github.com/popperjs/popper-core/blob/7cfd52de6fd1771bf8f772c8c21f25a212ff5b1a/src/modifiers/applyStyles.js#L43

**Comment by RonaldTreur** [comment]
I moved forward and created PR #1189 to prevent the code from setting a margin at all. I use Popper is various ways, and all of these use-cases continue to work as intended (according to expectations of course).

If you do see/expect issues with this, then please let me know!
