### ISSUE TITLE
Issues raised after code scan

### ISSUE THREAD

**Issue by Deepti0101** [popperjs/popper-core#1183]
Hi team, we have developed a page using popper js. Our clients performed "Fortify" scan and came up with few issues. Please find the attached report and help us find the solution.

[Popper_js_issues.pdf](https://github.com/popperjs/popper-core/files/5450598/Popper_js_issues.pdf)

**Comment by FezVrasta** [comment]
Popper doesn't include any encryption key, I don't understand what the report talks about. It looks like some automated tool thought that the minified Popper source code is a key itself.
