### ISSUE TITLE
position arrow to center

### ISSUE THREAD

**Issue by yaquawa** [popperjs/popper-core#1186]
## Feature description

currently it only allow absolute padding value:

```js
createPopper(reference, popper, {
  modifiers: [
    {
      name: 'arrow',
      options: {
        element: arrow,
        padding: 5, // I wish I can set this with '50%' to allow position in center
      },
    },
  ],
});
```

It is very common to position the arrow at the center of the element.

**Comment by FezVrasta** [comment]
I'd accept a PR to add support for a function like it happens with the `offset` modifier.

https://popper.js.org/docs/v2/modifiers/offset/#options

Example:

```ts
type Options = {
  padding: PaddingFunction | Padding,
};

type PaddingFunction = ({
  popper: Rect,
  reference: Rect,
  placement: Placement,
}) => Padding;
```

**Comment by atomiks** [comment]
The arrow is positioned at the center by default though?

**Comment by yaquawa** [comment]
@atomiks try to set the placement to `top-end`.

**Comment by yaquawa** [comment]
@FezVrasta Thanks. I haven't looked into the source code. If it's a easy fix, hope the team could add this feature in the next version👍🏼

**Comment by atomiks** [comment]
@yaquawa that's not something that needs dynamic positioning. You can set that in CSS yourself.
