### ISSUE TITLE
Test "__DEV__" in a browser compatible way.

### ISSUE THREAD

**Issue by Westbrook** [popperjs/popper-core#1188]
When attempting to get browser optimized builds of the library via `@popperjs/core/dist/esm/...` paths the files in question don't seem to have access to types that would be needed to leverage them in a Typescript project. Can the build process be tweaked to include this?

**Comment by Westbrook** [comment]
Alternatively, it would be really great to see the browser optimized build be the default `module` export instead of the development optimized build, which would allow to get both types and optimized code in the same place.

**Comment by FezVrasta** [comment]
You don't need to import the browser esm build with TS, you can use the default build

**Comment by Westbrook** [comment]
If I do that it comes out with `process.env` cruft. Was hoping there’d be a way to force TS to accept the types from the root for the `ESM` output, but I couldn’t find anything initially. I’m gonna ask around some more today, but it would be nice not to have some magic typing solution.

**Comment by FezVrasta** [comment]
If you use TS I suppose you use a build step, so you can tell it to strip out `process.env` from it.

**Comment by Westbrook** [comment]
`tsc`, the only native compiler for Typescript, will only address converting code from TS to JS and isn't involved in addressing any non-TS concepts when addressing your code. This means that the choice to leave detritus in the main `module` entry point while not allow access to types in the `esm` build makes it pretty awkward working with the library that is productive for end users that doesn't point towards then having a high probability of getting multiple compilations of it including in their final application build.

**Comment by FezVrasta** [comment]
So are you only transpiling your TS code with tsc but you are not doing any optimization step with webpack or rollup?

**Comment by Westbrook** [comment]
That's correct. This approach positions our users to make the most appropriate decisions regarding tranpilation/bundling/etc. based on their users. In the case that something like https://github.com/popperjs/popper-core/issues/933#issuecomment-582232301 were leveraged in the main module entry point, we'd all be pretty nicely served while being able to remove the ESM build all together, IMO.

**Comment by FezVrasta** [comment]
I see, feel free to send a PR to add types to the browser build too.

**Comment by Westbrook** [comment]
Thanks for being open to this. It feels like it would be slightly better to have the default entry point "just work" with types AND the browser, but if you prefer to expand the `dist/*` approach my understanding of what's going on right now is below...

Currently it looks like `yarn build:typescript` manages your types with the config in https://github.com/popperjs/popper-core/blob/master/.config/tsconfig.json. Would the correct path forward be to have a second config with `"outDir": "dist/esm"`? Seems like this would be restrictive to either have another config/call for each `cjs`, `esm` and `umd`. Alternatively, this could possibly leverage https://modern-web.dev/docs/building/rollup-plugin-copy/ or similar in the Rollup config (which would need to be run after the TS processing) to copy the already built definitions into each of the outputs it creates.

Thoughts?

**Comment by FezVrasta** [comment]
> Thanks for being open to this. It feels like it would be slightly better to have the default entry point "just work" with types AND the browser, but if you prefer to expand the `dist/*` approach my understanding of what's going on right now is below...

How would you go about this? We want to provide the dev-only error messages by default, for them to work we need access to `process.env`.

> Currently it looks like `yarn build:typescript` manages your types with the config in https://github.com/popperjs/popper-core/blob/master/.config/tsconfig.json. Would the correct path forward be to have a second config with `"outDir": "dist/esm"`? Seems like this would be restrictive to either have another config/call for each `cjs`, `esm` and `umd`. Alternatively, this could possibly leverage https://modern-web.dev/docs/building/rollup-plugin-copy/ or similar in the Rollup config (which would need to be run after the TS processing) to copy the already built definitions into each of the outputs it creates.

I think a simple `cp` command right after the TS types are generated should be enough? Wondering if symlinks would work too.

**Comment by Westbrook** [comment]
I'd like to think that replacing `if (__DEV__)` with `if (typeof process !== 'undefined' && process.env.NODE_ENV !== "production")` instead of `if (process.env.NODE_ENV !== "production")` would get you the same functionality at dev time with the ability to minify that out at the application level just the same? I'll look into that more in case you're interested.

I'll do set up a `cp` pass on the types in the interim.

**Comment by FezVrasta** [comment]
Yeah that would work too, maybe configure the babel transform to replace `__DEV__` with what you are proposing so we can keep using `__DEV__`

**Comment by TrySound** [comment]
It won't work. See my comment in PR. If you need popper scripts to work in browser without build step just define process.env.NODE_ENV globally before injecting this scripts.
