### ISSUE TITLE
Popper as a Web Component?

### ISSUE THREAD

**Issue by krhoyt** [popperjs/popper-core#1192]
## Feature description

What would Popper look like as a standards-based (as opposed to framework-centric) web component? Instead of pointing to a DOM element, composition could encapsulate the content to be displayed. Then maybe convenience methods for open() and close()?

## Why should this feature be part of the Popper's core?

Importing Popper into a web component, and then wrapping for the desired effect would probably be easy enough. Seems like a shortcut. Interested in discussion.

**Comment by FezVrasta** [comment]
There's no plan to provide a web component out of the box, this is left to 3rd parties willing to implement it.

**Comment by christianmartinnies** [comment]
@krhoyt I am about to do so. Wanna join? :)

**Comment by krhoyt** [comment]
@christianmartinnies This is still very interesting to me, but I do not have much time these days to work on it.
