### ISSUE TITLE
Debounce to be optional

### ISSUE THREAD

**Issue by monfera** [popperjs/popper-core#1194]
## Feature description

Looks like there's currently debounce. In some situations it's not desirable, eg. either or both of:
- the userland code also renders something that should be in sync with the thing, but in an unrelated part of the DOM tree
- the userland code rolls its own throttle/debounce optimization

## Why should this feature be part of the Popper's core?

Because `popper` is about being a lean positioning engine, and the debouncing or similar asynchronous steps in the logic make it less predictable and less controllable, while _not_ debouncing, or making it switchable, still allows the core logic to work, and authorize the user code to solve for this aspect.

**Comment by nickofthyme** [comment]
Related to: 
https://github.com/popperjs/popper-core/blob/264e2f31b1b0a765504aa4d4ee85ca0b0e319a9e/src/createPopper.js#L235-L243

**Comment by FezVrasta** [comment]
You can disable the events modifier and replace it with one that internally calls forceUpdate instead
