### ISSUE TITLE
Popover v2 overflows container

### ISSUE THREAD

**Issue by christianboyle** [popperjs/popper-core#1196]
### CodeSandbox demo

https://codesandbox.io/s/popper-2-playground-hgjuz (unaltered, steps to reproduce below)

### Steps to reproduce the problem

1. Visit https://getbootstrap.com/docs/4.5/components/popovers/#four-directions
2. Trigger "Popover on Left" and "Popover on Right"
3. Notice both adjust their position to be fully visible inside the body when viewport is sufficiently narrow
4. Visit https://getbootstrap.com/docs/5.0/components/popovers/#four-directions
5. Trigger "Popover on Left" and "Popover on Right"
6. Notice both overflow the body when viewport is sufficiently narrow

![456](https://user-images.githubusercontent.com/1605754/101505935-79d7bc00-393a-11eb-97e8-11a6b4ba92d9.png)

### What is the expected behavior?

Expected behavior is for popovers to not overflow their container (like in twbs 4.5.1).

### What went wrong?

It seems like there's been some change in the inline styles that are applied by Popper where we no longer perform the `transform: trasnlate3d(x, y, z)` and instead use `transform: translate(x, y)`.

![123](https://user-images.githubusercontent.com/1605754/101506119-ac81b480-393a-11eb-9643-7374e442dbb0.png)

I tried to locate where this might have changed recently, but it doesn't seem like this has been modified for ~12mo.: https://github.com/popperjs/popper-core/blame/671f71e2b6990765e5ca780daaea7d1f7175beb6/src/modifiers/computeStyles.js#L107

### Any other comments?

It's possible this bug is somehow coming from Bootstrap since both `4.5.1` and `5.0.0-beta1` use `"@popperjs/core": "^2.5.4",` in their `package.json`, but I'm not sure how this is possible due to the root issue being in the inline styles applied by Popper.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
