### ISSUE TITLE
Wrong popper width with overflow: auto

### ISSUE THREAD

**Issue by ptu14** [popperjs/popper-core#1198]
### CodeSandbox demo

https://codesandbox.io/s/pedantic-dijkstra-nl3xi

### Steps to reproduce the problem

1. Create a long list in the popper and set `max-height` to it
2. Set popper style "overflow-y: auto"
3. In Windows/Chrome87 resizing viewport makes the popper width count correctly. In Firefox remains unchanged.

### What is the expected behavior?
As I know this is a browser problem, the best solution I expect is a consistent and predictable popper behavior. But not resizing popper in Chrome when resizing viewport will be fine as well. Or maybe you have an idea of how to prevent this behavior on the user side.

### What went wrong?
The biggest problem is the wrong width in the modifiers.

### Any other comments?

Can be fixed quickly visually for Chrome. The fix for chrome is simple by setting e.g. popper `min-width`. But it's not work in Firefox.

It's a known browser bug: 
https://bugzilla.mozilla.org/show_bug.cgi?id=764076

it looks like the problem doesn't exist on macOS due to a different scrollbar

Windows/Chrome:
![image](https://user-images.githubusercontent.com/20875935/101608512-174bf200-3a06-11eb-9dc2-f3ab40115882.png)

MacOS/Chrome:
![image](https://user-images.githubusercontent.com/20875935/101609161-e91ae200-3a06-11eb-808f-1eb3bed38286.png)

**Comment by FezVrasta** [comment]
On a closer look this doesn't seem to have anything to do with Popper, the position is correctly computed, it's just that the browser decides to give the popper a size rather than another. There's nothing we can do for this.
