### ISSUE TITLE
initialStyles not affected by applyStyles

### ISSUE THREAD

**Issue by dellfort** [popperjs/popper-core#1201]
As a developer I want to use the popper library without CSP header **unsafe-inline**.
Therefore I need no inline styles to be applied to any DOM element.
To achieve this I use the the applyStyles modifier to catch the styles and write it to a <style> tag (which then has a `nonce` attribute and can be used without unsafe-inline CSP)
But unfortunately the **initialStyles** are still being applied to the element 

### CodeSandbox demo

https://codesandbox.io/s/old-platform-9y748?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce the problem

1. add applyStyle modifier

### What is the expected behavior?

No inline styles are applied to the target element

### What went wrong?

initial styles are still being applied to the element

**Comment by FezVrasta** [comment]
You also need to override the modifier's effect.

https://github.com/popperjs/popper-core/blob/1450aa5f1b113726f9b70d3d3b9ace53e1be290e/src/modifiers/applyStyles.js#L36-L75
