### ISSUE TITLE
npm install not working for popperjs

### ISSUE THREAD

**Issue by akshayp660** [popperjs/popper-core#1204]
PS C:\Users\Prafful\Desktop\Bhau\app> npm i @popperjs/core
Unrecognized token in source text.
At line:1 char:7
+ npm i  <<<< @popperjs/core
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnrecognizedToken

*this is output when i run npm command

**Comment by FezVrasta** [comment]
Pretty sure it's a problem with your machine.
