### ISSUE TITLE
Fixed position popper has positioning issues when using will-change

### ISSUE THREAD

**Issue by AndrewOCC** [popperjs/popper-core#1229]
### CodeSandbox demo
https://codesandbox.io/s/popperjs-willchange-positioning-9whyz?file=/src/index.css

### Steps to reproduce the problem

**The example replicates this scenario:**
1. Place popper and reference inside a parent with `will-change: width`
2. Use strategy: "fixed"
3. Scroll the page (I've placed the component in a scroll container in this example
4. Popper will not move with the reference

To observe issue in example
1. Scroll down (reload may be required, it appears semi-intermittently on codesandbox)
2. Go to `index.css` and comment out the marked line setting `will-change: width` in `.scrollContainer`
3. Popper should work fine when the line is commented out

### What is the expected behavior?

Popper should track the reference

### What went wrong?

Popper does not track the reference correctly, but does appear to shift as if trying to stay on screen when moving the reference out of the viewport.

### Any other comments?

This issue appears after version 2.4.1; was first spotted in a component using react-popper

**Comment by ptu14** [comment]
I create PR #1244 to fix this.
You can also workaround this using `transform: translate(0);` just after your `will-change: width;`. More in https://github.com/popperjs/popper-core/issues/1156
