### ISSUE TITLE
New placement - 'cover'

### ISSUE THREAD

**Issue by KutnerUri** [popperjs/popper-core#1232]
## Feature description

I used Popper to create a highlight effect, using a div with border and `pointer-events: none;`.
I think this could be a cool feature of Popper (or an official modifier), as it is uses a lot internals.

![image](https://user-images.githubusercontent.com/5400361/106747064-14e3ce00-662c-11eb-99e8-a4cc473b8745.png)

These are the 4 original modifiers I used to implement the feature:

```tsx
const popperModifiers = [
	ignorePopperSize,
	resizeToMatchReference,
	disableFlip,
	calcCoverCoordinates
];

// when calculating pop position, do not include popper-size
const ignorePopperSize: Modifier<string, {}> = {
	name: 'ignorePopperSize',
	enabled: true,
	phase: 'beforeRead',
	fn({ state }) {
		state.rects.popper = {
			...state.rects.popper,
			height: 0,
			width: 0,
		};
	},
}

export type ResizeToMatchReferenceOptions = {
	offset: [number, number];
};
const resizeToMatchReference: Modifier<string, ResizeToMatchReferenceOptions> = {
	name: 'resizeToMatchReference',
	enabled: true,
	phase: 'main',
	fn({ state, options }) {
		const { offset: [offsetX, offsetY] = [0, 0] } = options;
		const { width, height } = state.rects.reference;

		state.styles.popper = {
			...state.styles.popper,
			width: width + offsetX + 'px',
			height: height + offsetY + 'px',
		};
	},
};

const disableFlip = 	{
	name: 'flip',
	enabled: false,
};

// regular popper pops away from target, shift popper down to the target, + constants offest
const calcCoverCoordinates = {
	name: 'coverCoordinates',
	options: {
		// move box from above the target ('top-start')
		// to make sure border covers the target from the outside.
		offset: ({ reference }: any) => [BASE_OFFSET, BASE_OFFSET - reference.height],
	},
},
```

### Offset
In hindsight, there are two of sizes consumers will like to control:
* top/left shift (move the entire popper vertically or horizontally)
* "padding" (increase/decrease size of the popper in each of the directions)

though, If I had to be compatible with the existing offset props, I'd go with
```
offset={[ ±aspectRatioPx, ±distanceFromCenterPx ]}
```

What do you think? I'm open for anything

**Comment by FezVrasta** [comment]
That's so cool! Thanks for posting it. I think the best way to share this would be to publish your own npm package, there are some guidelines on our documentation: https://popper.js.org/docs/v2/modifiers/community-modifiers/
