### ISSUE TITLE
'fixed' strategy generates wrong position for 'top' placement on iOS/Android when URL bar is hidden

### ISSUE THREAD

**Issue by ProdanSergey** [popperjs/popper-core#1238]
Hi, Community!

There is an annoying bug on both iOS and Android browsers. When using 'fixed' strategy and placed a popper near the reference, the position is wrong. Looks like calculations don't consider URL bar height. 

Here is a sandbox with custom usePopper implementation. Try to open it in a full-screen on some mobile device.
https://codesandbox.io/s/popperjs-top-placement-mobile-bug-xxcwu

Steps to reproduce:

1. Scroll to the reference. In such way, the popper will use top placement. 
2. Ensures browser URL bar is hidden.
3.  Click the reference button. It will open-up a popper.

Expected result: 
The popover should be well-placed on the top of the reference.

Actual behaviour:
The popover is placed wrong. The Y-offset is wrong.

Tested OS's:
-- iOS@14.4
-- Android@7

Tested Browser's:
-- iOS Chrome@latest
-- iOS Safari - 14.4
-- Android Chrome Mobile - 71.0.357.99

Versions:
-- popper.js/core version is: 2.6.0

**Comment by FezVrasta** [comment]
Dupe of #1121?

**Comment by ProdanSergey** [comment]
Not exactly. Here you even shouldn't zoom a page.  I'm pretty sure it is related to wrong document height when mobile browsers URL TAB is going to disappear.

**Comment by FezVrasta** [comment]
With the absolute strategy everything works correctly on iOS so I don't think that's the issue.

**Comment by ProdanSergey** [comment]
Because the absolute position is base on the current container but not on the document.

**Comment by FezVrasta** [comment]
Absolute strategy can work with the document as container too.

**Comment by ProdanSergey** [comment]
Will check and update a sandbox. 👍

**Comment by FezVrasta** [comment]
Pretty sure it's a dupe of #1238

**Comment by FezVrasta** [comment]
Sorry, I meant to link to this one: #1136
