### ISSUE TITLE
Arrow modifier padding function miss-functionality 

### ISSUE THREAD

**Issue by GeoSot** [popperjs/popper-core#1254]
I am not sure if the new merged functionality on arrow modifier that accepts function as padding option, work fine
I have initiated  a popper in the below example. and tried the 

```js
placement: "right",
  modifiers: [
    {
      name: "arrow",
      options: {
        element: arrow,
        padding: ({ popper, reference, placement }) => {       
          console.log(popper, reference, placement);
          return "50%";
        }
      }
    }
  ]
```
As you can see in the below sandbox example the console, shows `  undefined   undefined "bottom" `
I am not sure if this correct, but placement also should be '**right**'

### CodeSandbox demo

https://codesandbox.io/s/intelligent-cherry-wp0bh?file=/src/index.js

### Steps to reproduce the problem

1. See the console 

### What is the expected behavior?
Probably 
**popper** & **reference** should not be undefined 
and **placement** has to be 'right'

**Comment by FezVrasta** [comment]
#1255 will fix it, but note that you are supposed to return an object (`top: x, right: y, bottom: z, left: k }`) or a number, you can't return a string like in your example.

**Comment by GeoSot** [comment]
of course. it is for the test only

**Comment by FezVrasta** [comment]
Yes it will fix everything.
