### ISSUE TITLE
Non-consistent export for commonjs and esm bundles

### ISSUE THREAD

**Issue by stenin-nikita** [popperjs/popper-core#1259]
### Steps to reproduce the problem

1. Import `@popperjs/core ' in the node environment
2. Output the "placements" variable to the console"

```js
const { placements } = require('@popperjs/core');

console.log(placements);
```

### What is the expected behavior?

API must be identical for commonjs and esm bundles.

### What went wrong?

The commonjs bundle does not match the esm bundle.

**Comment by FezVrasta** [comment]
`placements` is not exported by the library in either of the dist targets 🤷‍♂️ very consistent I'd say

**Comment by stenin-nikita** [comment]
@FezVrasta I don't agree with you.

CodeSandbox with typescript https://codesandbox.io/s/popperjs-exports-bb0vi?file=/src/index.ts

Take a look at the exports here: 
- https://unpkg.com/browse/@popperjs/core@2.8.6/lib/index.js
- https://unpkg.com/browse/@popperjs/core@2.8.6/dist/cjs/popper.js

Some libraries use module resolution based on these fields:
https://github.com/popperjs/popper-core/blob/master/package.json#L5-L7
