### ISSUE TITLE
setOptions() overrides previous modifiers

### ISSUE THREAD

**Issue by gtsiam** [popperjs/popper-core#1271]
### CodeSandbox demo code
```js
import { createPopper } from "@popperjs/core";

const button = document.querySelector("#button");
const tooltip = document.querySelector("#tooltip");

// Create a popper instance with some offset
let popper = createPopper(button, tooltip, {
  placement: "right",
  modifiers: [{ name: "offset", options: { offset: [0, 20] } }]
});

// Uncommenting the following will remove the offset
// popper.setOptions({
//   modifiers: [{ name: "eventListeners", enabled: true }]
// });
```

### Steps to reproduce the problem

1. Do `createPopper()` with an offset modifier
2. Call `setOptions()` to enable/disable listeners
3. The offset is now gone

### What is the expected behavior?
I would expect existing modifiers to be unaffeted

### What went wrong?
The offset is now gone

### Any other comments?
My expectations come from the [tutorial](https://popper.js.org/docs/v2/tutorial/), where the behavior I expect is described. However pasting the tutorial's full code into codepen, shows no offset.

This could be a documentation issue, since the actual [tutorial code](https://github.com/popperjs/website/blob/20486276739e5bfa9e18855ad96f33eaa711d08d/src/components/Tutorial.js#L153) is different than the one displayed. But since I can't find any clear documentation for `setOptions()`, I will assume it is a bug.

**Comment by FezVrasta** [comment]
That's a documentation issue, my bad, `setOptions` overrides all the options with the new ones.

**Comment by himanshu007-creator** [comment]
Hi , i would like to work on this issue. Please guide me what changes are required to be done

**Comment by FezVrasta** [comment]
It's enough to update the documentation on the website, the example should include the whole config each time setOptions is called

**Comment by gtsiam** [comment]
I was _kinda_ planning to do it, but I kept putting it off since I don't really need it anymore, so... you're welcome to

You'll have to rewrite the tutorial to reflect the actual behavior of `setOptions()`. That means either:
- Removing references to disabling the event listeners (This is what [the actual demo code](https://github.com/popperjs/website/blob/20486276739e5bfa9e18855ad96f33eaa711d08d/src/components/Tutorial.js#L153) does)
- Rewriting the code to work properly

But it's kinda hard for me to make the call, so... @FezVrasta ?

**Comment by rohit2sharma95** [comment]
Or maybe you can update the `setOptions` method to merge the passed configuration? :thinking:
But that would be a breaking change IMO

**Comment by FezVrasta** [comment]
I haven't included an auto-merge functionality because it would increase a lot the size of the library, I'd rather left this to the consumer if they ever need it.

**Comment by FezVrasta** [comment]
I added an option to pass a function to setOptions that will work very similarly to how React's state setters work.

https://popper.js.org/docs/v2/constructors/#setoptions
