### ISSUE TITLE
Popper position is not correct on iOS mobile app

### ISSUE THREAD

**Issue by Sitronik** [popperjs/popper-core#1279]
### Steps to reproduce the problem

1. Run ionic 5 with vue 3 environment for development
2. Add the popper library to your ionic application
3. Compile the code for iOS and run in mobile or emulator

### What is the expected behavior?

Should work in the iOS mobile application the same as in the browser

### What went wrong?

1. I am developing a cross-platform mobile application using the ionic framework and I found that the positioning of the popper in the iOS mobile application is not correct

2. In the popper instance, I found that in the `state.rects.reference.y` object
property `y` - is not correct In the browser, y is `1825.78125` but in iOS mobile app is `227.4375`

3. It turned out that the problem is that the getOffsetParent function returns the wrong parent element. 
In the browser, this is the `main` html element from the shadow DOM. This is the correct element and everything works as expected, but on iOS this is the `ionic-content` element

### Any other comments?

To fix this problem I added this code to getOffsetParent function and now everything works

```javascript
if (offsetParent && offsetParent.tagName === 'ION-CONTENT') {
  offsetParent = document.querySelector('ion-content').shadowRoot.querySelector('main')
}
```
Oddly enough, but on android mobile app and in the browser in Safari on IOS get OffsetParent function work correct

A little later I will send a PR with this fix

### Video on which popper works correctly in the browser
https://user-images.githubusercontent.com/7203872/115143689-7de6b980-a051-11eb-88f6-62c7e19a7c02.mov

### Video where the popper does not work correctly in the iOS mobile app
https://user-images.githubusercontent.com/7203872/115143711-9951c480-a051-11eb-9bd9-cf1929823570.mov

**Comment by FezVrasta** [comment]
I don't plan to add framework specific logic, the issue is with Ionic and the way it works in a non standard way
