### ISSUE TITLE
Regression of #611 - Bootstrap table-responsive

### ISSUE THREAD

**Issue by realnot** [popperjs/popper-core#1282]
As tittle says I guess this is a regression of #611 - Filter columns are not visible when you click the dropdown arrow.

https://jsfiddle.net/0ex91L46/

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
