### ISSUE TITLE
Dropdown menu is hidden when used with "table-responsive"

### ISSUE THREAD

**Issue by realnot** [popperjs/popper-core#1283]
### CodeSandbox demo

https://codesandbox.io/s/magical-diffie-6ljqb?file=/index.html

### Steps to reproduce the problem

1. Click on filter dropdown toggle next to the input element

### What is the expected behavior?

The dropdown menu should go out of table to display completely

### What went wrong?

The opened dropdown menu is hidden from table

### Any other comments?

I added bootstrap css and js through CDN because I don't know how to add them through dependencies using the suggested tool. Maybe a regression of #611 ?

If you remove div tag with class "table-responsive" (opening tag at row 28, closing tag at row 249) the dropdown works as expected.

Here the bootstrap link [https://getbootstrap.com/docs/5.0/content/tables/#responsive-tables](https://getbootstrap.com/docs/5.0/content/tables/#responsive-tables) with the warning 

> Vertical clipping/truncation
> Responsive tables make use of overflow-y: hidden, which clips off any content that goes beyond the bottom or top edges of the table. In particular, this can clip off dropdown menus and other third-party widgets.

**Comment by FezVrasta** [comment]
Hi, repros need to use **only** Popper, I'm not going to debug Bootstrap's code.

**Comment by realnot** [comment]
Hi thanks for your quick reply and your time. Do you think is bootstrap bug or related to popper.js? This one was fixed prior to version 2?

**Comment by FezVrasta** [comment]
I don't know, without a proper repro I can't do anything

**Comment by realnot** [comment]
Here another sandbox with just css: [https://codesandbox.io/s/prod-flower-64vr2?file=/index.html](https://codesandbox.io/s/prod-flower-64vr2?file=/index.html)

Is not always reproducible

OK:

[![Schermata-2021-04-21-alle-22-27-47.png](https://i.postimg.cc/nhqZfCJS/Schermata-2021-04-21-alle-22-27-47.png)](https://postimg.cc/18RbpR4D)

With the bug:

[![Schermata-2021-04-21-alle-22-30-02.png](https://i.postimg.cc/J0yV6hxq/Schermata-2021-04-21-alle-22-30-02.png)](https://postimg.cc/2LfK3rPb)

Is hard to reproduce it

**Comment by FezVrasta** [comment]
Why are you using such an old Popper version?

**Comment by realnot** [comment]
I tried to figure how when this bug it's been fixed to provide more information and test cases. I opened another issue on bootstrap because after many attempt looks like this it's been fixed in 2.0.0-rc.1 and appear only when I add bootstrap css/js libs from CDN, so I can exclude popper.js to generate this bug I guess. I'll try to investigate more. Thanks again for you time!
