### ISSUE TITLE
InternetExplorer does not support array.find()

### ISSUE THREAD

**Issue by bsever** [popperjs/popper-core#1297]
### CodeSandbox demo

https://codesandbox.io/s/popper-2-playground-hgjuz

### Steps to reproduce the problem

1. Open example in InternetExplorer

### What is the expected behavior?

Popperjs works in InternetExplorer as well

### What went wrong?

InternetExplorer does not support array.find() method. In 3 places this not supported is used.

**Comment by FezVrasta** [comment]
https://popper.js.org/docs/v2/browser-support/#ie11
