### ISSUE TITLE
Yet another subpixel rounding issue [Safari 14.0.3]

### ISSUE THREAD

**Issue by axyz** [popperjs/popper-core#1300]
Hi, I saw that there are many issues about subpixel rendering and that a lot of impressive work was done to cover all the edge cases, so I'm not sure if this is already a known problem.

On Safari, both on iphone and on mac with hidpi display the popper element gets misaligned by half a pixel when the reference is positioned on a decimal (e.g. 104.5px) x coordinate.

<img width="1118" alt="Screenshot 2021-05-04 at 14 36 18" src="https://user-images.githubusercontent.com/412723/117005503-9e687200-ace7-11eb-9f0f-bb2d51ae6d28.png">

### CodeSandbox demo

https://codesandbox.io/s/wizardly-shadow-j0lui

In this sandbox the problem is reproduced using a minimal popper-lite setup and hardcoding the position of the reference to a decimal value

### Steps to reproduce the problem

open the codesandbox on this environment:

Mac OS 11.2.3
Safari 14.0.3
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
devicePixelRatio = 2

### What is the expected behavior?

the left borders of the reference and the popper should be perfectly aligned and look like a continuous line

### What went wrong?

The line is broken because the popper is misaligned in relation to the reference
### Any other comments?

It seems to work correctly if the values are not rounded, my understanding is that rounding or not depends on a series of conditions (dpi, user agent, gpu, etc...) and maybe this is a missed corner case where rounding should be disabled?

cc. @sylvesteraswin

**Comment by atomiks** [comment]
The addition of the second inner `round` function in this PR causes this issue: https://github.com/popperjs/popper-core/pull/1213/files#diff-93b86d40b54cd42a9ed1d0fce7e9d45604dc82b0159e0125dadee470211b4c3dL39-R45

**Comment by Westbrook** [comment]
I've got an alternative PR for this that _might_ help: https://github.com/popperjs/popper-core/pull/1418 It seems that the rounding only happened on the way into the `mapToStyles` method and then non-rounded numbers were used to modify them before sending values to the client. Rounding at the end, right before sending to the client, seems to give more predicable results here.
