### ISSUE TITLE
Tooltip with arrow causes vertical scrollbar in IE11

### ISSUE THREAD

**Issue by joshuajaco** [popperjs/popper-core#1311]
### CodeSandbox demo

https://codesandbox.io/s/admiring-elion-465ew

### Steps to reproduce the problem

1. add a tooltip that is positioned above the trigger
2. add an arrow that overflows out the bottom of the tooltip
3. open tooltip

### What is the expected behavior?

No vertical scrollbar

### What went wrong?

The problem is caused by using `bottom: 0`. Other browser get that the arrow is no longer positioned at the bottom of the page due to the `transform: translate(...);`, however IE11 seems to think the arrow is overflowing the page regardless.

<details>

<summary>
Minimal HTML reproduction
</summary>

```html
<html>

<head>
    <style>
        .tooltip {
            bottom: 0;
            position: absolute;
            transform: translate(500px, -500px);
            background: green;
        }

        .arrow {
            position: absolute;
            top: 100%;
            border-style: solid;
            border-width: 0.4rem 0.5rem 0 0.5rem;
            border-color: green transparent transparent transparent
        }
    </style>
</head>

<body>
    <div class="tooltip">tooltip content<div class="arrow"></div>
    </div>
</body>

</html>
```

</details>

### Any other comments?

Not sure why popper is using `bottom: 0` instead of `top: 0` for tooltips positioned above the trigger. A fix would be to always use `top: 0` but I'm not sure what else would be affected by that. Or possibly there is a work around that doesn't involve changing the behaviour of popper, however I did not find one. The solution we are using in our project now is to simply hide the arrow for IE11 users completely.

**Comment by FezVrasta** [comment]
Please try to turn off the `adaptive` option.

https://popper.js.org/docs/v2/modifiers/compute-styles/#adaptive

**Comment by joshuajaco** [comment]
Setting `adaptive` to false indeed solved our problem 👍
Thanks for the quick reply. 
Maybe it makes sense to mention this on the [browser support page](https://popper.js.org/docs/v2/browser-support/)
