### ISSUE TITLE
When I use popper with element-ui select x-placement attribute not change bottom-start to top-start.

### ISSUE THREAD

**Issue by brkcvn** [popperjs/popper-core#1313]
<img width="499" alt="Screen Shot 2021-05-25 at 09 46 03" src="https://user-images.githubusercontent.com/22003497/119451566-16054c00-bd3e-11eb-952c-767c5822b06a.png">

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
