### ISSUE TITLE
Typings for built-in/core modifiers

### ISSUE THREAD

**Issue by LoganDark** [popperjs/popper-core#1327]
I'm running into an issue with TypeScript typings, namely I don't know what to do in the function here:

```typescript
	{
		name: 'arrow',
		options: {
			element: arrow,
			padding: ({popper, reference, placement}) => {
				// ...
			}
		}
	},
```

My compiler is screaming at me that the parameters aren't typed, I don't know what the type is, I know nothing about them except that two of them have a `width` property... I can barely work with this, it's going to take me a lot longer to figure out what is going on than it would have if these modifiers had been typed (so I could've done something like `options: {...} as ArrowModifierOptions`)

So here is my feature request for typing these, so future developers can be productive in TypeScript when they want to do super advanced things like, having the arrow point at a different element than the top level reference :/

**Comment by FezVrasta** [comment]
Modifiers should already be typed, here's an example:

https://unpkg.com/browse/@popperjs/core@2.9.2/lib/modifiers/arrow.d.ts

**Comment by LoganDark** [comment]
> Modifiers should already be typed, here's an example:
> 
> https://unpkg.com/browse/@popperjs/core@2.9.2/lib/modifiers/arrow.d.ts

Ah, the reason I don't have that must be because I only have react-popper. Even though `@popperjs/core` is installed, since it's not in my package.json I can't use types from it.

Adding `@popperjs/core` to my `package.json` allowed me to slap `as ArrowModifier` on the modifier item and that fixed the issue, thank you!
