### ISSUE TITLE
removeOnDestroy doesn't take effect in v2

### ISSUE THREAD

**Issue by danail-vasilev** [popperjs/popper-core#1329]

**Comment by FezVrasta** [comment]
It's not supported on 2.x

**Comment by danail-vasilev** [comment]
thanks FezVrasta!
Is there are feature request opened for it ?
Also what is the workaround for v2 ?

**Comment by FezVrasta** [comment]
No there aren't any plans to reintroduce it, we removed any logic that wasn't strictly related to positioning. You should look into Tippy.js for a full fledged tooltip library if you are looking for this kind of features.

**Comment by danail-vasilev** [comment]
Thanks for your reply!
I am actually using popper.js as a plugin for cytoscape.js - https://github.com/cytoscape/cytoscape.js-popper
This is one of the main approaches for aligning HTML over cytoscape graph. We need to recreate/destroy graphs dynamically based on selected that and hence destroy the overlayed popper HTML as well.
Regarding tippy.js, cytoscape has already a demo with it but it depends on popper.js - it is a complement not a substitute.
That being said removeOnDestroy property seems very useful and generic.

**Comment by FezVrasta** [comment]
You can easily achieve the same functionality:

```js
const popperElement = popperInstance.state.elements.popper;
popperInstance.destroy();
popperElement.remove();
```

**Comment by danail-vasilev** [comment]
Thank you !
