### ISSUE TITLE
Offsets not working with Shadow DOM

### ISSUE THREAD

**Issue by chadwtkns** [popperjs/popper-core#1345]
### CodeSandbox demo

https://codepen.io/chadwtkns/pen/WNjqgaW

https://jsfiddle.net/b83ygvn9/6/

### Steps to reproduce the problem

1. Create element with Shadow DOM
2. Use offset modifer (any numbers in offset)
3. Tooltip not reacting to changes

### What is the expected behavior?

I would expect that when I offset by any number that the tooltip would have moved

**Comment by atomiks** [comment]
Popper v1 is no longer maintained. Have you tried this with v2?
