### ISSUE TITLE
`update()`, `forceUpdate()`, and resize event are not working properly when `gpuAcceleration` is `false`

### ISSUE THREAD

**Issue by danlevy1** [popperjs/popper-core#1349]
### CodeSandbox demo

https://codesandbox.io/s/reverent-elgamal-8tpgf?file=/src/index.js

### Steps to reproduce the problem

I used Google Chrome version `92.0.4515.159` to reproduce the issue.

1. Place the reference element (i.e. button) on the right side of its container.
1. Set `gpuAcceleration` to `false`.
2. Change the content (inner HTML) of the popper element (e.g. tooltip) after it is first rendered to cause a size change (width and/or height).
3. Call `update()` or `forceUpdate()` on the `popperInstance`.
4. Notice that the popper element (e.g. tooltip) is not re-rendered correctly [this is the bug].
5. Scroll the page.
6. Notice that the popper element (e.g. tooltip) is re-rendered correctly.
7. Refresh the page.
8. Resize the page instead of scrolling.
9. It appears that resizing does not always re-render the popper element properly. When I use my Mac's trackpad to zoom in (i.e. pinch-to-zoom), the resize event works properly, but if I zoom in using the keyboard (e.g. `cmd` + `+`), the resize event does not work properly. Zooming back out using the keyboard (e.g. `cmd` + `-`), re-renders the popper element properly.

### What is the expected behavior?

When the size of the popper element changes (e.g. due to its content changing), `update()`, `forceUpdate()`, and resizing re-renders the same way the `scroll` event re-renders the popper element.

Note that setting `gpuAccelaration` to `true` (its default value) does work properly.

### What went wrong?

Calling `update()`, `forceUpdate()`, or resizing the page does not re-render the popper element in the same way the `scroll` event does.

### Any other comments?

For our use-case, we need to turn GPU acceleration off because we have seen blurriness issues in some browsers with GPU acceleration turned on (the blurriness issue has been reported before).

**Comment by atomiks** [comment]
This appears fixed in the latest version

**Comment by danlevy1** [comment]
Awesome! Just tried it out in version `2.10.2` and it looks good. Thanks for the great work!
