### ISSUE TITLE
Incorrect popper placement when using Lightning Web Components on Safari/Firefox

### ISSUE THREAD

**Issue by dk-andyet** [popperjs/popper-core#1350]
Hi there,

I've been having some issues where the `transform: translate()` would have some incorrect calculations on the popper element when using Safari/Firefox (but would be ok with chrome). Specifically, the popper would open up when a button is clicked but would be near the bottom of the page (Y-axis would be calculated WAY off only on Safari or Firefox).

I know this is a shot in the dark, but does anyone have an idea what might be causing this?

unfortunately, I am having issues trying to reproduce the issue with Codepen as I am using Lightning Web Components.

Thanks!

**Comment by FezVrasta** [comment]
Sales Force implements its own DOM interface and it's not always up to spec. We introduced workarounds to overcome its issues in the past but I don't plan to do anything like that anymore.
