### ISSUE TITLE
Recent change to package.json/exports causes an issue in @restart/ui which breaks other downstream projects

### ISSUE THREAD

**Issue by ajohnson-ventera** [popperjs/popper-core#1361]
the change (https://github.com/popperjs/popper-core/pull/1342) seems to break this usage in some way.

### What is the expected behavior?

The enums should have been found by webpacks with alternate imports.

When using imports like this https://github.com/react-restart/ui/blob/main/src/popper.ts#L9 should work

### What went wrong?

```
ModuleNotFoundError: Module not found: Error: Package path ./lib/enums is not exported from package
.../Library/Caches/Bit/capsules/2b25412ad92805e9573583d4b25e6a7e05d89fd5/node_modules/@restart/ui/node_modules/
@popperjs/core (see exports field in .../Library/Caches/Bit/capsules/2b25412ad92805e9573583d4b25e6a7e05d89fd5/node_modules/@restart/ui/node_modules/
@popperjs/core/package.json)
```

**Comment by evanleck** [comment]
I'm seeing something similar when using esbuild to bundle modifiers directly.

```
 > app/assets/scripts/tooltip.js:2:47: error: Could not resolve "@popperjs/core/lib/modifiers" (mark it as external to exclude it from the bundle)
     2 │ import { arrow, offset, preventOverflow } from '@popperjs/core/lib/modifiers'
       ╵                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   node_modules/@popperjs/core/package.json:29:13: note: The path "./lib/modifiers" is not exported by package "@popperjs/core"
    29 │   "exports": {
```

**Comment by ajohnson-ventera** [comment]
Yeah I'm sure this will affect a lot of projects.

**Comment by EschlerLam** [comment]
Yeha it affects quite a bit. We had to lock all of our projects on v2.9.3 to mitigate. Thank you FezVrasta for the quick response to this. Please let us know if there is anything you need from us.

**Comment by crokodz** [comment]
yep same here, need to npm remove @popperjs/core and npm install @popperjs/core@2.9.3 in my pipeline just to get it working

**Comment by crokodz** [comment]
> Yeah I'm sure this will affect a lot of projects.

yes, quite frustrating when you don't know what is happening and you got a production deployment just like now.

**Comment by crokodz** [comment]
> Yeah I'm sure this will affect a lot of projects.

yes, quite frustrating when you don't know what is happening and you got a production deployment just like now.

**Comment by marcosguilhermef** [comment]
If you are using 2.10.0, I suggest that you change to 2.9.2.

**Comment by marcosguilhermef** [comment]
This is the code snippet that causes the bug. It's in package.json:
(2.10.0)
"exports": {
    ".": {
      "node": {
        "import": "./lib/index.js",
        "default": "./dist/cjs/popper.js"
      },
      "browser": {
        "import": "./dist/esm/popper.js",
        "default": "./dist/umd/popper.js"
      }
    },
    "./package.json": "./package.json"
  }

**Comment by FezVrasta** [comment]
I released a new version that reverts this, sorry for the trouble
