### ISSUE TITLE
Include dist/lib with repository

### ISSUE THREAD

**Issue by danisztls** [popperjs/popper-core#1377]
## Feature description
Include lib/dist files within repository for flexible import. Those can be placed in `lib` and `dist` in the repository so the user can use whatever he wants to manage the dependency instead of being forced to use Node.js/NPM.

## Why should this feature be part of the Popper's core?
Forcing the use of Node/NPM for importing is limiting and not lean.

**Comment by FezVrasta** [comment]
There's no plan to do that, git is meant to store source code, not artifacts
