### ISSUE TITLE
Nuxt 3: To load an ES module, set "type": "module" in the package.json

### ISSUE THREAD

**Issue by lukaszflorczak** [popperjs/popper-core#1407]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@popperjs/core@2.10.2` for the project I'm working on.

I tried to use popper in Nuxt 3 project, but I found a problem with importing `createPopper`:

```
(node:11549) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/lukaszflorczak/project/node_modules/@popperjs/core/lib/enums.js:1
export var top = 'top';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@popperjs/core/package.json b/node_modules/@popperjs/core/package.json
index d4edd3a..e0e5975 100644
--- a/node_modules/@popperjs/core/package.json
+++ b/node_modules/@popperjs/core/package.json
@@ -26,6 +26,7 @@
     "/dist",
     "/lib"
   ],
+  "type": "module",
   "sideEffects": false,
   "scripts": {
     "clean": "rimraf lib && rimraf dist && rimraf test/visual/dist",
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by atomiks** [comment]
Dupe just opened: https://github.com/popperjs/popper-core/issues/1406

According to that, `type: "module"` would be a breaking change for CJS contexts, i.e. Jest?

**Comment by jd-0001** [comment]
Is there any workaround for using it with nuxt3?

**Comment by lukaszflorczak** [comment]
@jd-0001 I used https://github.com/ds300/patch-package as described in the first post. By `patch-package` you can modify dependencies from `node_modules` in safe way . The changes are in your repository as patch files and `patch-package` runs them in dependencies `post install` stage, so the whole team use it without any additional action. Probably now it's the only way.

**Comment by jd-0001** [comment]
Hi @lukaszflorczak Thanks for reply.

I tried `npx patch-package @popperjs/core` but I am getting:
```
patch-package 6.4.7
• Creating temporary folder
• Installing @popperjs/core@2.11.0 with yarn
• Diffing your files with clean files
⁉️  Not creating patch file for package '@popperjs/core'
⁉️  There don't appear to be any changes.
```

With change same as yours:
```diff
+  "type": "module",
   "sideEffects": false,
```

![Screenshot 2021-11-30 at 3 07 31 PM](https://user-images.githubusercontent.com/47495003/144022408-f1c2b933-e311-4d73-a531-bd33b36dbaa2.png)

**Comment by jd-0001** [comment]
Solved!

I have to run: `npx patch-package --exclude 'nothing' @popperjs/core`

**Comment by fosterdouglas** [comment]
Commenting here to say that this was extremely useful to me!

In particular, using Nuxt3 and was trying to get a bootstrap 5 Dropdown (popper.js) working properly. The patch-package process worked great.

Thank you both.
