### ISSUE TITLE
Popper element is not aligned to trigger, off by 1px

### ISSUE THREAD

**Issue by OliverJAsh** [popperjs/popper-core#1410]
### CodeSandbox demo

https://stackblitz.com/edit/react-nyp2yj?file=src%2FApp.js

Clonable repo: https://github.com/OliverJAsh/popper-subpixel-issue

### Steps to reproduce the problem

When we view this test case at odd viewport sizes e.g. 327px wide in this example, the popper element is not aligned to the trigger. It is off by ~1 px.

![image](https://user-images.githubusercontent.com/921609/141187940-6205386e-0232-4051-a08c-0865aa1ff1cf.png)

Zoomed in slightly:

![image](https://user-images.githubusercontent.com/921609/141188001-72cabd70-c8fd-4dd2-b6b8-de3a7b8fad51.png)

**Comment by atomiks** [comment]
Does https://github.com/popperjs/popper-core/pull/1400 fix it?

**Comment by OliverJAsh** [comment]
I just tested. It helps but it doesn't completely solve the issue.

Without #1400:

![image](https://user-images.githubusercontent.com/921609/141235613-55de31dc-d635-4e0a-b7e1-b85e2f4c9ba1.png)

https://user-images.githubusercontent.com/921609/141235630-0ab1a544-0d5a-4a12-9c5e-6d641adc8137.mov





With #1400:

![image](https://user-images.githubusercontent.com/921609/141235517-e5ce5469-1958-430d-ac2d-e7c766e10563.png)

https://user-images.githubusercontent.com/921609/141235559-05a3eadc-8d51-4c93-ade3-63175fe7df08.mov

**Comment by atomiks** [comment]
I wonder if using `floor()` for `*-start` placements, and `ceil()` for `*-end*` placements works in that function?

**Comment by atomiks** [comment]
The following works for me:

```js
function roundOffsetsByDPR({x, y}) {
  const win: Window = window;
  const dpr = win.devicePixelRatio || 1;

  // Don't round by DPR for variation placements
  if (variation) {
    return {
      x: round(x),
      y: round(y),
    };
  }

  return {
    x: round(x * dpr) / dpr,
    y: round(y * dpr) / dpr,
  };
}

```
