### ISSUE TITLE
Official popper wrap for vue/nuxt 3

### ISSUE THREAD

**Issue by jd-0001** [popperjs/popper-core#1419]
## Feature description

As popper already has an official react wrapper, I love to see the official vue 3 wrapper w/ nuxt support.

## Why should this feature be part of the Popper's core?

This shouldn't be in the core but it should have separate repo like react version.

**Comment by FezVrasta** [comment]
Hi, I don't have any experience with Vue so I wouldn't be able to create a good wrapper and maintain it. There are several solutions on npm though.

**Comment by iamandrewluca** [comment]
https://github.com/allindevelopers/vue-floating-ui

**Comment by Akryum** [comment]
https://github.com/Akryum/floating-vue
