### ISSUE TITLE
Tooltip position gets shifted when switched into Fullscreen mode

### ISSUE THREAD

**Issue by omairnabiel** [popperjs/popper-core#1421]
Tooltip position is shifted when toggled into fullscreen mode

https://user-images.githubusercontent.com/13148988/144441094-cde7fba4-ae8f-4f4e-9d11-ffd2f81eea51.mov

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
