### ISSUE TITLE
platform.isRTL VirtualElement support

### ISSUE THREAD

**Issue by dgeibi** [popperjs/popper-core#1555]
getComputedStyle require a Element:

https://github.com/floating-ui/floating-ui/blob/d8a90be987a2479743e8e16c6319ca6c5b3c739e/packages/dom/src/platform.ts#L27

**Comment by atomiks** [comment]
Good catch. If the DOM platform was strongly typed it would have caught this; all the args are `any`-typed due to being agnostic
