### ISSUE TITLE
`@floating-ui/react` 0.18.0 and up missing `@floating-ui/dom` dependency causing issues with Yarn PnP

### ISSUE THREAD

**Issue by jdpt0** [popperjs/popper-core#2156]
Change introduced here: https://github.com/floating-ui/floating-ui/compare/%40floating-ui/react%400.17.0...%40floating-ui/react%400.18.0#diff-1cee8646d2cfba37d6ce6a6e9a8d16f8caba0b99fc3a1ad0cb997ed8c7384d2e

`@floating-ui/dom` needs to be added as a dependency to `@floating-ui/react`.

**Comment by atomiks** [comment]
Importing them from `react-dom` instead of `dom` should work the same, PR is welcome if you want
