### ISSUE TITLE
Popper position is wrong with transform: scale

### ISSUE THREAD

**Issue by kaflake** [popperjs/popper-core#376]
Hi,
wenn I set a transform to scale in the style, positioning of the popup element is wrong. Here is a short example in CodePen:
https://codepen.io/FezVrasta/pen/MWbvEjg

I think it use now scaled positions and sizes to calculate the popup position, but else it should use still orginal size, cause the transform value also effect on the popup

**Comment by FezVrasta** [comment]
Thanks for the bug report, there's definitely something wrong in this case.

**Comment by maxpaj** [comment]
I think it could be because Popper wants to set the `transform` to position the element. If you then override the transform with a `scale` then old transform is no longer being applied...

**Comment by nomoon** [comment]
I worked around this by modifying `getBoundingClientRect()` function to solve for the pre-scaled value`

https://github.com/FezVrasta/popper.js/blob/master/packages/popper/src/utils/getBoundingClientRect.js#L37-L42:
```
 var scale = rect.width / element.offsetWidth;
  var result = {
    left: Math.round(rect.left / scale),
    top: Math.round(rect.top / scale),
    width: Math.round((rect.right - rect.left) / scale),
    height: Math.round((rect.bottom - rect.top) / scale)
  };
```

**Comment by FezVrasta** [comment]
Cool! Would you mind to send a PR with your change?

**Comment by nomoon** [comment]
@FezVrasta: Absolutely. I realize that scale can be different in X and Y so I should probably calculate those separately. Also, since getBoundingClientRect can return floats, I’m not entirely sure if I should round things at this point? I suspect rounding might prevent half-pixel issues for when top/left is used instead of translate.

**Comment by guidupuy** [comment]
Hey, wondering why this is marked as closed? 

I'm having a similar issue with a library using popper under the hood (Tippy), and the CodePen example still shows the popper misplaced even though it uses the latest version of popper.

**Comment by FezVrasta** [comment]
I must have referenced the wrong issue ID.

**Comment by Devil-Cong** [comment]
Hey, Is there have any good solution now?
when I use scale...
![image](https://user-images.githubusercontent.com/13516290/89486864-991cdc00-d7d6-11ea-871a-a4c9677fbd93.png)
![image](https://user-images.githubusercontent.com/13516290/89486870-9de19000-d7d6-11ea-8483-41dcc114f410.png)

**Comment by rakeshpai** [comment]
Just ran into this issue. I think @maxpaj is right. Setting any `transform` style is overridden by popper to set the `translate3d` to position the element. In my case, the `transform: scale` is being used in a CSS animation `from` `scale(0.8)` `to` `scale(1)` for a little pop effect. So, I don't think I can even do something in a modifier to fix this issue.

Interesting that this is essentially a problem because `transform` is pretty overloaded in CSS.

If anyone has a good solution to this problem, I'll be happy to create a PR. The solution would have to work with animations, since I think animating popups would be a somewhat common use-case.

Maybe the best solution is to not use `transform: translate3d` and instead use some other positioning method?

**Comment by yarastqt** [comment]
A decided this issue for my project, i'm creating modifier with `beforeRead` phase and applying patch for `state.rects.reference`.

**patchScaleFactor.ts**

```ts
import { Modifier } from '@popperjs/core'
import getLayoutRect from '@popperjs/core/lib/dom-utils/getLayoutRect'

export const patchScaleFactor: Modifier<'patchScaleFactor', {}> = {
  enabled: true,
  name: 'patchScaleFactor',
  phase: 'beforeRead',
  requires: ['popperOffsets'],
  fn: ({ state }) => {
    if (state.elements.reference instanceof HTMLElement) {
      state.rects.reference = getLayoutRect(state.elements.reference)
    }
  },
}
```

Demo with modifier for [CodeSandbox](https://codesandbox.io/s/sparkling-paper-t10by?file=/src/Popup.js:746-762)

**Comment by allex** [comment]
> Just ran into this issue. I think @maxpaj is right. Setting any `transform` style is overridden by popper to set the `translate3d` to position the element. In my case, the `transform: scale` is being used in a CSS animation `from` `scale(0.8)` `to` `scale(1)` for a little pop effect. So, I don't think I can even do something in a modifier to fix this issue.
> 
> Interesting that this is essentially a problem because `transform` is pretty overloaded in CSS.
> 
> If anyone has a good solution to this problem, I'll be happy to create a PR. The solution would have to work with animations, since I think animating popups would be a somewhat common use-case.
> 
> Maybe the best solution is to not use `transform: translate3d` and instead use some other positioning method?

you can disable `gpuAcceleration` to prevent this behavior:

```
      var options = {
        modifiers: [{
          name: 'computeStyles',
          options: {
            gpuAcceleration: false // true by default
          }
        }]
      };
```

**Comment by KutnerUri** [comment]
just ran into this when using together with React Flow Renderer
![image](https://user-images.githubusercontent.com/5400361/106741838-e8788380-6624-11eb-8f7d-3e4b159a6ca4.png) (regular scale)
![image](https://user-images.githubusercontent.com/5400361/106741832-e6aec000-6624-11eb-8d56-9236b5452015.png) (zoomed out)

Scale (and transforms in general) seems to mess with Popper's size calculations.
I went around it by using interactive={false}:
![image](https://user-images.githubusercontent.com/5400361/106742277-810f0380-6625-11eb-88ee-2d7405689967.png)

I thought I would get similar results with `useSingleton()`, without losing interactivity, but apparently the singleton refers to the Popper instance, and not the DOM element :(

**Comment by atomiks** [comment]
@KutnerUri `appendTo={document.body}` should work?

**Comment by KutnerUri** [comment]
@atomiks yes! been looking for it everywhere.
It also prevents parent `<a>` tags from making a link out of the tooltip.

I'm having some trouble with `useSingleton()`, it does not want to override it for some reason.
But this is good enough, I'll setup a mount point under the theme provider. :)

**Comment by FezVrasta** [comment]
I prepared a PR to fix this (#1247) but some tests fail, specifically, the ones that test reference elements with a `transform: scale(...)` style. It looks like we should conditionally apply the scaling logic to `getBoundingClientRect`. If someone wants to fix my PR please feel free to.

**Comment by atomiks** [comment]
Looks like the above logic should only be applied if the popper & reference are in the same scaled parent.

**Comment by Auk14HP** [comment]
Has there been any progress concerning this issue?
