### ISSUE TITLE
IE11 provoke popper's 'update' on control got focus, different to Chrome and Edge

### ISSUE THREAD

**Issue by rpokrovskij** [popperjs/popper-core#627]
https://codepen.io/rpokrovskij/pen/XqzaWg?editors=1111

Press "Click me"
Result is "menu stay at place" on Chrome and Edge when on IE 11 "menu position is changed".

Expected result: consistent behavior (I prefer "no update position" in all browsers)

**Comment by wnr** [comment]
@rpokrovskij I'm experiencing similar problems. Did you find a workaround for this?

**Comment by rpokrovskij** [comment]
@wnr no, just leave with it.

**Comment by FezVrasta** [comment]
May someone verify if this is still an issue with `@popperjs/core@alpha`?

**Comment by rpokrovskij** [comment]
> May someone verify if this is still an issue with `@popperjs/core@alpha`?

I could, just give me an url (cdn)?

**Comment by FezVrasta** [comment]
You can find it at https://unpkg.com/@popperjs/core@alpha, but there's no integration with Bootstrap yet, so you will need to reproduce the issue without Bootstrap's JavaScript.

**Comment by rpokrovskij** [comment]
Thank you. 
is an `Uncaught TypeError: Popper is not a constructor` problem part of this 'Boostrap's JS missing integration problem?

I got it after 

       ` <script src="https://unpkg.com/@popperjs/core@2.0.0-alpha.3/dist/umd/popper.min.js"></script>`

**Comment by FezVrasta** [comment]
The Popper api changed, you now call it with Popper.createPopper(...)

**Comment by rpokrovskij** [comment]
When new Popper works in Chrome In IE11 we get SCRIPT438: Object doesn't support property or method 'assign'
popper.min.js (5,1317)

somewhere there

```
let state: $Shape<State> = {
      placement: 'bottom',
      orderedModifiers: [],
      options: { ...defaultOptionsValue, ...defaultOptions },
      modifiersData: {},
      elements: {
        reference: referenceElement,
        popper: popperElement,
      },
      attributes: {},
      styles: {},
    };
```

BTW how to set those parameters with new `createPopper`?

 popper=new Popper( 
            choiceFilterInputElement, 
            choicesElement, 
            {
                placement: 'bottom-start',
                modifiers: {
                    preventOverflow: {enabled:false},
                    hide: {enabled:false},
                    flip: {enabled:false}
                }
            }
        );

now this provokes errors smth like "unexpected parameter"...

**Comment by atomiks** [comment]
@rpokrovskij 

For IE11 you need polyfills, [docs here](https://github.com/popperjs/popper.js/blob/next/docs/src/pages/docs/browser-support.mdx)

Passing modifiers config has changed, [docs here](https://github.com/popperjs/popper.js/blob/next/docs/src/pages/docs/modifiers/prevent-overflow.mdx#mainaxis)

**Comment by rpokrovskij** [comment]
Polyfill works, but issue is still present.

https://dashboardcode.github.io/BsMultiSelect/snippetPopper.html

**Comment by atomiks** [comment]
The only way `.update()` gets called is via `resize` and `scroll` listeners (or manually invoking the method), so my assumption here is IE11 is firing one of those events upon focus. Can you add listeners on the window for `resize` and `scroll` and log them to see what's firing?

**Comment by rpokrovskij** [comment]
done. there are no scroll or resize events on IE11 (as well as on Chrome )
https://dashboardcode.github.io/BsMultiSelect/snippetPopper.html

**Comment by FezVrasta** [comment]
I just tested this out in IE11 and I can't reproduce the issue.

Probably there's something in your setup that is causing this issue.

![Kapture 2020-01-17 at 16 47 26](https://user-images.githubusercontent.com/5382443/72625486-2b4bb880-3949-11ea-8877-5dc5c32d0434.gif)

**Comment by rpokrovskij** [comment]
Hi, thank you for try. It is strange. Which version of IE11 you use? Mine is 11.973.17763.0 

Also what is the name of software to produce such gifs?

**Comment by rpokrovskij** [comment]
Ok I got it. To reproduce there should be not focus in input!

**Comment by rpokrovskij** [comment]
> I just tested this out in IE11 and I can't reproduce the issue.
> 
> Probably there's something in your setup that is causing this issue.
> 
> ![Kapture 2020-01-17 at 16 47 26](https://user-images.githubusercontent.com/5382443/72625486-2b4bb880-3949-11ea-8877-5dc5c32d0434.gif)

Please reopen or get me the info that you have read the information above

**Comment by FezVrasta** [comment]
I can’t reproduce even when the input is not focused, I’m quite sure it’s something in your system

**Comment by atomiks** [comment]
@FezVrasta is right, tried various combinations, never happens: https://imgur.com/a/a8AX1ll

**Comment by rpokrovskij** [comment]
Bad for me. It is interesting that this bug happens only when input was never focused. once it was focused (and lost focus) - the menu stay in place...  And the bug doesn't happen on disabled input.

**Comment by rpokrovskij** [comment]
@atomiks  could you test it on "full screen" IE11 ? I just have found that after I minize IE11 screen "for screen capture app" bug was disappear. But return on full screen. Craziness.

**Comment by atomiks** [comment]
Went full screen; still can't reproduce at all. Likely difference is due to IE versions.

The one in the VM I downloaded from MS is 11.914.x

Highly doubt there is anything we can do regardless so no point discussing this further imo

**Comment by rpokrovskij** [comment]
@atomiks hang on, I do not want to discuss it, I want to help you to improve the lib and knowledge base.

**Comment by atomiks** [comment]
Logging inside the `update()` method should help, it should also receive an event object when an event listener calls it
