### ISSUE TITLE
GitHub Organization and package names

### ISSUE THREAD

**Issue by FezVrasta** [popperjs/popper-core#844]
I just created a new GitHub Organization: github.com/popperjs

I'd like to transfer there both github.com/FezVrasta/popper.js and github.com/FezVrasta/react-popper
I suppose this will make it easier for new contributors to join and better manage the project without waiting for me to take actions.

I'd also like to rename the npm packages to make it easier to consume and recognize them. A lot of people complained because of the `.js` part of the package name, so I think a good solution would be (as suggested by @atomiks):

- `@popperjs/core`, where the core JavaScript library will live;
- `@popperjs/react`, where `react-popper` will be moved;

Do you think this reorg would help with the current situation?

**Comment by FezVrasta** [comment]
I just finished moving react-popper and popper.js under the new popperjs organization.

Now I wonder if it would make sense to rename the repositories to:

- github.com/popperjs/core
- github.com/popperjs/react

I'm not quite sure about this because having a repository called `react` may make people think that's a fork of `facebook/react` 🤷‍♂

**Comment by atomiks** [comment]
What about a monorepo with this current repo name you have? So packages are `/core` and `/react`

**Comment by FezVrasta** [comment]
I don't think I would find any benefit in putting under the same repo the two projects, they use completely different technologies, build pipelines, etc...

**Comment by embeddedt** [comment]
I think, to avoid confusion, you need `popper` in the React package's name as well. Maybe stick with `@popperjs/react-popper`?
