### ISSUE TITLE
Is there a plan to add lifecycle events in 2.0?

### ISSUE THREAD

**Issue by tylergraf** [popperjs/popper-core#950]
In v1, there was an `onCreate` and `onUpdate` callback function. Is there a plan for that in v2?

I managed to get the `onCreate` using a modifier with the `afterWrite` phase, but it doesn't seem ideal.

**Comment by FezVrasta** [comment]
What’s your use case? `createPopper()` and ` instance.update()` returns a promise with the updated state.

**Comment by FezVrasta** [comment]
My bad, it doesn’t 😅 I’ll work on it

**Comment by tylergraf** [comment]
Cool. I think a promise would be great.

**Comment by atomiks** [comment]
`update()` returns a promise: https://jsfiddle.net/ugeoLy6m/

`createPopper()` doesn't however

**Comment by FezVrasta** [comment]
I added a new section about lifecycle here: https://popper.js.org/docs/v2/lifecycle

I also just pushed a commit to add `onFirstUpdate` to the allowed options, which will be called after the first update is ran.

This should cover all the use cases of the old `onCreate` and `onUpdate`.

**Comment by a7medm7med** [comment]
hj
