### ISSUE TITLE
Inner Modifier

### ISSUE THREAD

**Issue by bennymeier** [popperjs/popper-core#965]
Hi!

Where is the inner modifier in version 2.0? Is there another simple way to position the popper inside an element on every placement like in version 1.0?

**Comment by atomiks** [comment]
You can use the `offset` modifier with negative values, it also allows you to read the dimensions of each element.

**Comment by FezVrasta** [comment]
Something like this should do it.

https://codesandbox.io/s/epic-silence-i7680

**Comment by bennymeier** [comment]
Thanks guys for your fast response. Okay so I have to do it myself, I was just asking because maybe your planning to implement it again as a modifier.

**Comment by FezVrasta** [comment]
We plan to keep the core leaner, and promote 3rd party modifiers more. If you are up to it, you may publish your own inner modifier as a dedicated npm package.

**Comment by marcusx2** [comment]
@FezVrasta I saw the example but I didn't quite get it. Where in the code it mentions "screen" or anything like that? How is it making the element relative to the screen?

**Comment by FezVrasta** [comment]
You should be able to set the document or window elements as target.
