### ISSUE TITLE
Release package doesn't contain dist files

### ISSUE THREAD

**Issue by lauriii** [popperjs/popper-core#967]
I tried to download the release from https://github.com/popperjs/popper-core/releases/tag/v2.0.0 but it doesn't seem to include the dist files. I was able to build these manually but it would be useful if the dist files were directly available in the package available on the release page.

**Comment by FezVrasta** [comment]
Hi, please read [the dedicated section](https://popper.js.org/docs/v2/#3-direct-download) in our documentation.

Git is not the place where to store compiled assets.
