### ISSUE TITLE
scrollbar not calculated correctly, causing an overflow

### ISSUE THREAD

**Issue by And7s** [popperjs/popper-core#969]
Positioning a tooltip very close to the viewport boundary can cause an overflow.

https://jsfiddle.net/bzs7yfq4/1/

https://imgur.com/a/FPnbu21

## Observation
Positioning a tooltip close to the boundary clips the tooltip and causes an overflow.

## Expectation

The tooltip is flipped to the left to not cause the page to overflow. This happens after resizing the viewport further. 
Coincidentally the issue happens over a span of the scrollbar width. 
Potentially the scrollbar width is not taken into consideration on positioning.

```
popper version: 2.0.0
chrome:  79.0.3945.117 
macOS 10.14.6
```

**Comment by FezVrasta** [comment]
I think scrollbar sizes should be used here https://github.com/popperjs/popper-core/blob/master/src/utils/detectOverflow.js#L81-L90

@atomiks I remember you, at some point, implemented the scrollbar logic, but then removed it. May you add some context please?

**Comment by atomiks** [comment]
`getClippingRect` should add the scrollbars. I am guessing it only works correctly inside scrolling containers :\\ https://github.com/popperjs/popper-core/blob/76dfc39c96c70cf6f07b434a4c7a34011b462bc7/src/dom-utils/getClippingRect.js#L69-L71 

When it's `Window` the check is skipped, but we probably want to use `documentElement` to consider the scrollbars instead. macOS with the autohiding scrollbars made it easy to not encounter this even though I've turned on always frequently while developing... will send a PR shortly
