### ISSUE TITLE
clippingParents for popper in body

### ISSUE THREAD

**Issue by semeleven** [popperjs/popper-core#986]
## Feature description
Now `clippingParents` works fine, when popper is siblings with reference. But when popper in the body, `clippingParents` calculate body is a parent. But it is not what I expect. I expect to calculate reference overflow parent in this case. I think will be good to add some flag, like `inBody`, to calculate parents from reference. Now we have `altBoundary` flag, but it is, as far as I understand, for another mission.

## Why should this feature be part of the Popper's core?
Render popper in the body, I think, a common case when people work with overflow containers. Now we have `preventOverflow` modifier for overflow case. If handmade set right overflow parent to `boundary` - all fine. But I think, will be better has current sugar `clippingParents` for this case.

**Comment by FezVrasta** [comment]
Thanks for the report, may you provide an example ([you can use this sandbox](https://codesandbox.io/s/popper-2-playground-hgjuz)) to help me understand what are you proposing?

**Comment by atomiks** [comment]
`"scrollParent"` in v1 was a very problematic default, see: https://github.com/codesandbox/codesandbox-client/issues/3059

`altBoundary` is fine to use if you want it to check the reference's `"clippingParents"` instead.
