### ISSUE TITLE
Prevent overflow `tether` property doesn't work as expected 

### ISSUE THREAD

**Issue by lauriii** [popperjs/popper-core#989]
### JSFiddle demo
https://jsfiddle.net/lauriii/qrh2nozv/10/

### Steps to reproduce the problem

1. Scroll down on the demo
2. Ensure that tooltip doesn't remain on top of the iframe

### What is the expected behavior?
Based on the documentation, I would assume that the tooltip remains on top of the iframe/window like in this demo: https://jsfiddle.net/lauriii/qrh2nozv/11/.

### What went wrong?
The tooltip remains tethered to the reference element.

### Any other comments?
If I set the prevent overflow `altAxis` property to `true`, the tooltip behaves as expected. Based on the documentation, it isn't clear why this would be required.

**Comment by atomiks** [comment]
That's expected — only the `mainAxis` (`x` for top/bottom) is checked by default, so it won't be tethered in that scenario without enabling `altAxis`. 

Also the `fixed` strategy is recommended for this scenario to prevent jittering (especially in Safari, although it has some other problems with `fixed` 🙁)

**Comment by lauriii** [comment]
That definitely helps explain why this is needed, thank you! 👍 This also seems to be documented in the `mainAxis` section. For some reason I missed that part and I assumed the `mainAxis` to be `y` for top/bottom placement.
