### ISSUE TITLE
What are the downsides of popperjs?

### ISSUE THREAD

**Issue by nainardev** [popperjs/popper-core#997]
## Feature description

So I'm just wondering what are the downsides to it over others, or just downsides?
(Note: I :heart:  this library)

Similar to (https://github.com/preactjs/preact/issues/2199)

**Comment by atomiks** [comment]
The main one I think is **bundle size**

Even though we dropped a fair amount of size (over 1.5 kB minzipped) and made it tree-shakable for v2, I think a "simple positioning library" weighing over 5 kB minbrotli with all its features (default) is too much still. Ideally a lot of the code we're writing would be abstracted into a browser API similar to `IntersectionObserver` (like all of `getClippingRect` and its dependencies) so we can call that API instead, cutting out at least 1 kB worth of code. But there's nothing like that that will work for the library. Not to mention you'd need to polyfill that API which defeats the purpose in many browsers 🤷‍♂ 

There are tons of problems and edge cases we have to solve + features that we need to support that makes it difficult to ever get below a certain size. That is, if people want these things to "just work" without problems, as well as keeping parity with v1 features. You can get a lighter library if you want to manually think about the edge cases where the solution will break, or lacks a lot of key features/extensibility. Lighter libraries either don't handle these edge cases or lack features/extensibility, or perform poorly.

People are welcome to submit PRs to strip out unnceccessary / refactor code to reduce the size 😄

**Comment by nainardev** [comment]
Also, Why some libraries (like `bootstrap` uses older versions of popper. Why not   `popper@2`?

**Comment by atomiks** [comment]
Popper 2 was only released last month. Bootstrap has been using Popper 1 since 2017; it takes time for projects to migrate to the new version since it has a fair few breaking changes, and they may need to also increment their own major in the process due to it if they provided direct access to Popper APIs, further delaying the migration

**Comment by FezVrasta** [comment]
Thanks @atomiks  for the answers, I’m gonna close this ticket because it’s not about a bug or enhancement as defined by the issues guidelines of the project. Feel free to continue on our Spectrum community
